Repository faker-js/faker, pull requests merged in 2022-04, with the labels that each got.

#745 chore: removed outcommented dead code in commerce.ts
  src/commerce.ts
Labels: p: 1-normal, s: accepted

#737 fix: deterministic results for address.nearbyGPSCoordinate
  src/address.ts
  test/address.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#671 chore: update codeowners file
  .github/CODEOWNERS
Labels: c: chore, p: 2-high, s: accepted

#748 refactor(address): drop local references of faker modules
  src/address.ts
Labels: p: 1-normal, s: accepted, c: refactor

#744 chore: downgrade min npm version from 7 to 6
  package.json
Labels: c: feature, p: 1-normal

#749 chore: remove useless fallback to undefined
  src/faker.ts
Labels: c: chore, p: 1-normal

#752 chore: remove invalid country code files
  src/definitions/address.ts
  src/locales/fa/address/country_code.ts
  src/locales/fa/address/index.ts
  src/locales/he/address/country_code.ts
  src/locales/he/address/country_code_alpha_3.ts
  src/locales/he/address/index.ts
  test/all_functional.spec.ts
Labels: c: bug, c: docs, c: chore, p: 2-high

#755 chore: fix warning in helpers replaceCreditCardSymbols
  src/helpers.ts
Labels: c: chore, p: 1-normal

#746 test: add a general country iban test
  test/finance_iban.spec.ts
Labels: p: 1-normal, c: test

#756 chore: add updateLocaleFileHook to generateLocales
  scripts/generateLocales.ts
Labels: c: chore, p: 1-normal

#763 chore: remove issue-labeling.yml
  .github/workflows/issue-labeling.yml
Labels: c: chore, p: 1-normal, s: accepted

#764 refactor: rename hexaDecimal to hexadecimal
  src/datatype.ts
  src/finance.ts
  src/random.ts
  test/datatype.spec.ts
  test/random.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#765 test: check that system.filePath() generates file extensions
  test/system.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#760 chore: address zipCodeByState fix types
  src/address.ts
  src/definitions/address.ts
  src/locales/ar/address/index.ts
  src/locales/ar/address/postcode_by_state.ts
  src/locales/en/address/index.ts
  src/locales/en/address/postcode_by_state.ts
  src/locales/he/address/index.ts
  src/locales/he/address/postcode_by_state.ts
  src/locales/ur/address/index.ts
  src/locales/ur/address/postcode_by_state.ts
  test/address.spec.ts
Labels: c: chore, p: 1-normal, s: accepted

#766 chore: deprecate name.title() in favor of name.jobTitle()
  src/name.ts
  test/name.spec.ts
Labels: c: chore, p: 1-normal

#753 chore: fix mustache type warning and add some tests
  src/helpers.ts
  test/helpers.spec.ts
Labels: c: chore, p: 1-normal

#767 refactor: remove inconsistent defaults from internet.password()
  src/internet.ts
Labels: p: 1-normal, c: refactor

#774 test: fix random alpha and alphaNumeric tests assumptions
  test/random.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#773 chore(release): 6.1.2
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: p: 1-normal, c: release, s: accepted

#685 feat: add some en locale city prefixes and suffixes
  src/locales/en/address/city_prefix.ts
  src/locales/en/address/city_suffix.ts
  test/address.spec.ts
  test/helpers.spec.ts
Labels: p: 1-normal, s: accepted, c: locale

#573 feat: append more korean dataset and delete wrong dataset
  src/locales/ko/address/city_name.ts
  src/locales/ko/address/street_root.ts
  src/locales/ko/name/first_name.ts
Labels: p: 1-normal, c: locale

#243 feat: add Lastname - Bhadresha, Jangid, Suthar
  src/locales/en_IND/name/last_name.ts
Labels: p: 1-normal, c: locale

#698 refactor(helpers.shuffle): remove unused default value
  src/helpers.ts
Labels: p: 1-normal, s: accepted, c: refactor

#588 refactor(address.countryCode): signature
  src/address.ts
Labels: p: 1-normal, c: refactor

#253 chore: additional domain suffixes added for GB locale
  src/locales/en_GB/internet/domain_suffix.ts
Labels: p: 1-normal, c: locale

#784 chore: simplify lorem.sentences()
  src/lorem.ts
Labels: c: chore, p: 1-normal

#783 fix: use `\n` as default separator for lorem.paragraphs()
  src/lorem.ts
  test/lorem.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#754 feat: use street address templates from locales
  src/address.ts
  src/definitions/address.ts
  src/locales/ar/address/street_address.ts
  src/locales/az/address/street_address.ts
  src/locales/cz/address/street_address.ts
  src/locales/de/address/street_address.ts
  src/locales/de_AT/address/street_address.ts
  src/locales/en/address/street_address.ts
  src/locales/en_GH/address/street_address.ts
  src/locales/es/address/street_address.ts
  src/locales/es_MX/address/street_address.ts
  src/locales/fa/address/street_address.ts
  src/locales/fr/address/street_address.ts
  src/locales/fr_BE/address/street_address.ts
  src/locales/ge/address/street_address.ts
  src/locales/he/address/street_address.ts
  src/locales/hr/address/street_address.ts
  src/locales/hy/address/street_address.ts
  src/locales/id_ID/address/street_address.ts
  src/locales/it/address/street_address.ts
  src/locales/lv/address/street_address.ts
  src/locales/mk/address/street_address.ts
  src/locales/nb_NO/address/street_address.ts
  src/locales/nl/address/street_address.ts
  src/locales/nl_BE/address/street_address.ts
  src/locales/pl/address/street_address.ts
  src/locales/pt_PT/address/street_address.ts
  src/locales/ro/address/street_address.ts
  src/locales/ru/address/street_address.ts
  src/locales/sk/address/street_address.ts
  src/locales/sv/address/street_address.ts
  src/locales/tr/address/street_address.ts
  src/locales/uk/address/street_address.ts
  src/locales/ur/address/street_address.ts
  src/locales/zh_CN/address/street_address.ts
  src/locales/zh_TW/address/street_address.ts
Labels: c: feature, p: 1-normal, s: accepted

#640 feat: add os. as street prefix for pl
  src/locales/pl/address/street_prefix.ts
Labels: p: 1-normal, s: accepted, c: locale

#781 chore: fix finance.iban warnings
  src/iban.ts
Labels: c: chore, p: 1-normal

#266 feat: extend list of domain suffix for PL locale
  src/locales/pl/internet/domain_suffix.ts
Labels: p: 1-normal, c: locale

#277 feat: add chinese hyphenated name
  src/locales/zh_CN/name/last_name.ts
Labels: p: 1-normal, c: locale

#695 feat: faker.finance.pin()
  src/finance.ts
  test/finance.spec.ts
Labels: c: feature, p: 1-normal

#616 feat: Add MongoDB ObjectId generation
  src/database.ts
  test/database.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#786 chore: lorem uses faker.helpers
  src/lorem.ts
Labels: c: chore, p: 1-normal, s: accepted

#785 chore: IBAN library typed and moved to utils
  scripts/bundle.ts
  src/finance.ts
  src/utils/iban.ts
  test/finance.spec.ts
  test/finance_iban.spec.ts
Labels: c: chore, p: 1-normal, s: accepted

#789 chore: finance use faker.helpers
  src/finance.ts
Labels: c: chore, p: 1-normal, s: accepted

#639 chore: renovate ru locales
  src/locales/ru/company/prefix.ts
  src/locales/ru/company/suffix.ts
  src/locales/ru/name/female_first_name.ts
  src/locales/ru/name/female_middle_name.ts
  src/locales/ru/name/male_first_name.ts
  src/locales/ru/name/male_middle_name.ts
Labels: p: 1-normal, c: locale

#793 test: add parameter defaults to our signature generation test
  scripts/apidoc.ts
  scripts/apidoc/utils.ts
  test/scripts/apidoc/signature.example.ts
  test/scripts/apidoc/signature.expected.json
  test/scripts/apidoc/signature.spec.ts
Labels: c: docs, p: 1-normal, c: test, s: accepted

#811 docs: nice literal unions
  scripts/apidoc/moduleMethods.ts
  scripts/apidoc/signature.ts
  test/scripts/apidoc/signature.debug.ts
  test/scripts/apidoc/signature.example.ts
  test/scripts/apidoc/signature.expected.json
  test/scripts/apidoc/signature.spec.ts
  test/scripts/apidoc/utils.ts
Labels: c: docs, p: 1-normal, s: accepted

#807 chore: fix todo comments
  src/name.ts
Labels: c: chore, p: 1-normal, s: accepted

#804 fix: Maryland (MD) wrong postal code
  src/locales/en_US/address/postcode_by_state.ts
Labels: c: bug, p: 1-normal, s: accepted

#792 feat: special characters in emails
  src/internet.ts
  test/internet.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#817 chore: use consistent method calls
  src/address.ts
  src/commerce.ts
  src/company.ts
  src/datatype.ts
  src/finance.ts
  src/helpers.ts
  src/image.ts
  src/internet.ts
  src/lorem.ts
  src/name.ts
  src/random.ts
  src/system.ts
Labels: c: chore, p: 1-normal, s: accepted

#814 docs: nice string literals
  scripts/apidoc/apiDocsWriter.ts
  scripts/apidoc/signature.ts
  scripts/apidoc/utils.ts
  test/scripts/apidoc/signature.example.ts
  test/scripts/apidoc/signature.expected.json
Labels: c: docs, p: 1-normal, s: accepted

#798 refactor: datatype number
  src/datatype.ts
  test/datatype.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#810 refactor: improve unique
  src/unique.ts
  src/utils/unique.ts
  test/unique.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#790 feat: immutable options in random.alpha methods
  src/random.ts
  test/random.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#828 refactor: log messages for unique fields
  docs/.vitepress/tsconfig.json
  src/unique.ts
  test/scripts/apidoc/tsconfig.json
  tsconfig.json
Labels: p: 1-normal, c: refactor

#829 feat: phone IMEI
  src/phone.ts
  test/phone.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#822 feat: dynamic definitions tree
  src/definitions/definitions.ts
  src/faker.ts
  test/faker.spec.ts
Labels: c: feature, p: 1-normal

#368 feat: add more arabic names datasets
  src/locales/ar/name/male_first_name.ts
Labels: p: 1-normal, c: locale

#844 feat: extend list of street prefixes for pl locale
  src/locales/pl/address/street_prefix.ts
Labels: p: 1-normal, c: locale

#504 feat: add internet.emoji
  src/definitions/internet.ts
  src/internet.ts
  src/locales/en/internet/emoji.ts
  src/locales/en/internet/index.ts
  src/locales/fa/internet/index.ts
  test/internet.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#732 chore: prefer string templates over string concatenation
  .eslintrc.js
  scripts/apidoc/apiDocsWriter.ts
  scripts/apidoc/signature.ts
  scripts/generateLocales.ts
  scripts/verifyCommit.ts
  src/address.ts
  src/commerce.ts
  src/datatype.ts
  src/fake.ts
  src/finance.ts
  src/git.ts
  src/helpers.ts
  src/image.ts
  src/image_providers/lorempicsum.ts
  src/image_providers/lorempixel.ts
  src/image_providers/unsplash.ts
  src/internal/deprecated.ts
  src/internet.ts
  src/lorem.ts
  src/mersenne.ts
  src/name.ts
  src/system.ts
  src/utils/user-agent.ts
  test/all_functional.spec.ts
  test/finance_iban.spec.ts
Labels: c: chore, p: 1-normal

#836 docs: fix lost description texts
  docs/.vitepress/theme/index.css
  scripts/apidoc/signature.ts
  src/internet.ts
  src/time.ts
  test/scripts/apidoc/signature.example.ts
  test/scripts/apidoc/signature.expected.json
Labels: c: bug, c: docs, p: 1-normal

#854 refactor: readonly default modules
  src/faker.ts
Labels: c: refactor

#857 fix: dont log deprecations on startup
  src/unique.ts
  test/faker.spec.ts
Labels: c: bug, p: 2-high, s: accepted

#861 chore(release): 6.2.0
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: p: 1-normal, c: release, s: accepted

#53 feat: add Hungarian locale
  docs/api/localization.md
  src/locale/hu.ts
  src/locales/hu/animal/cat.ts
  src/locales/hu/animal/dog.ts
  src/locales/hu/animal/horse.ts
  src/locales/hu/animal/index.ts
  src/locales/hu/commerce/color.ts
  src/locales/hu/commerce/department.ts
  src/locales/hu/commerce/index.ts
  src/locales/hu/commerce/product_description.ts
  src/locales/hu/commerce/product_name.ts
  src/locales/hu/date/index.ts
  src/locales/hu/date/month.ts
  src/locales/hu/date/weekday.ts
  src/locales/hu/finance/account_type.ts
  src/locales/hu/finance/index.ts
  src/locales/hu/finance/transaction_type.ts
  src/locales/hu/index.ts
  src/locales/hu/internet/domain_suffix.ts
  src/locales/hu/internet/free_email.ts
  src/locales/hu/internet/index.ts
  src/locales/hu/name/female_first_name.ts
  src/locales/hu/name/first_name.ts
  src/locales/hu/name/index.ts
  src/locales/hu/name/last_name.ts
  src/locales/hu/name/male_first_name.ts
  src/locales/hu/name/name.ts
  src/locales/hu/name/prefix.ts
  src/locales/hu/phone_number/formats.ts
  src/locales/hu/phone_number/index.ts
  src/locales/hu/word/adjective.ts
  src/locales/hu/word/adverb.ts
  src/locales/hu/word/conjunction.ts
  src/locales/hu/word/index.ts
  src/locales/hu/word/interjection.ts
  src/locales/hu/word/noun.ts
  src/locales/hu/word/verb.ts
  src/locales/index.ts
Labels: p: 1-normal, s: accepted, c: locale

#864 docs: make clear that latitude is first on nearbyGPSCoordinate
  src/address.ts
Labels: c: docs, p: 1-normal, s: accepted

#865 test: strengthen price regex tests
  test/commerce.spec.ts
  test/finance.spec.ts
Labels: p: 1-normal, c: test

#800 feat: resettable unique store
  src/unique.ts
  src/utils/unique.ts
  test/unique.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#852 test: use consistent assertion functions
  test/address.spec.ts
  test/commerce.spec.ts
  test/company.spec.ts
  test/datatype.spec.ts
  test/fake.spec.ts
  test/finance.spec.ts
  test/finance_iban.spec.ts
  test/git.spec.ts
  test/hacker.spec.ts
  test/helpers.spec.ts
  test/internet.spec.ts
  test/lorem.spec.ts
  test/name.spec.ts
  test/phone.spec.ts
  test/random.spec.ts
  test/system.spec.ts
  test/vehicle.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#681 feat: configure eol character for git.commitEntry
  src/git.ts
  test/git.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#797 feat: random numeric
  src/random.ts
  test/random.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#868 test: add seeded tests for random module
  test/random.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#877 refactor(word): extract wordlist filter in separate method
  src/word.ts
Labels: p: 1-normal, s: accepted, c: refactor

#874 feat: faker.helpers.maybe
  src/helpers.ts
  test/helpers.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#876 fix: address.nearbyGPSCoordinate
  src/address.ts
  test/address.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#885 chore: remove deprecated methods from fake tests
  test/fake.spec.ts
Labels: c: chore, p: 1-normal, c: test, s: accepted

#503 feat: separate methods for object key value
  src/finance.ts
  src/helpers.ts
  src/random.ts
  test/helpers.spec.ts
  test/random.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#888 feat: add creditCardIssuer
  src/definitions/finance.ts
  src/finance.ts
  test/finance.spec.ts
Labels: c: feature, p: 1-normal, s: accepted
