Repository faker-js/faker, pull requests merged in 2022-05, with the labels that each got.

#853 feat: return seed value from seed()
  src/faker.ts
  test/address.spec.ts
  test/animal.spec.ts
  test/commerce.spec.ts
  test/company.spec.ts
  test/database.spec.ts
  test/datatype.spec.ts
  test/date.spec.ts
  test/faker.spec.ts
  test/finance.spec.ts
  test/finance_iban.spec.ts
  test/git.spec.ts
  test/hacker.spec.ts
  test/helpers.spec.ts
  test/internet.spec.ts
  test/lorem.spec.ts
  test/music.spec.ts
  test/name.spec.ts
  test/phone.spec.ts
  test/random.spec.ts
  test/system.spec.ts
  test/time.spec.ts
  test/unique.spec.ts
  test/vehicle.spec.ts
  test/word.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#892 refactor: move some random methods to helpers
  src/address.ts
  src/animal.ts
  src/commerce.ts
  src/company.ts
  src/database.ts
  src/datatype.ts
  src/date.ts
  src/fake.ts
  src/finance.ts
  src/git.ts
  src/hacker.ts
  src/helpers.ts
  src/image.ts
  src/image_providers/lorempixel.ts
  src/internet.ts
  src/lorem.ts
  src/music.ts
  src/name.ts
  src/phone.ts
  src/random.ts
  src/system.ts
  src/utils/user-agent.ts
  src/vehicle.ts
  src/word.ts
  test/helpers.spec.ts
  test/internet.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#894 test: add tests
  src/helpers.ts
  test/helpers.spec.ts
Labels: p: 1-normal, c: test, s: needs decision

#901 chore(release): 6.3.0
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: c: release

#903 fix: replace deprecated arrayElement calls
  src/random.ts
  test/fake.spec.ts
  test/unique.spec.ts
Labels: c: bug

#905 chore(release): 6.3.1
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: c: release

#907 chore: add examples and improve jsdocs for datatype.datetime
  src/datatype.ts
Labels: c: chore, p: 1-normal

#910 chore: remove obsolete definition key constants
  src/definitions/address.ts
  src/definitions/animal.ts
  src/definitions/commerce.ts
  src/definitions/company.ts
  src/definitions/database.ts
  src/definitions/date.ts
  src/definitions/definitions.ts
  src/definitions/finance.ts
  src/definitions/hacker.ts
  src/definitions/index.ts
  src/definitions/internet.ts
  src/definitions/lorem.ts
  src/definitions/music.ts
  src/definitions/name.ts
  src/definitions/phone_number.ts
  src/definitions/system.ts
  src/definitions/utils.ts
  src/definitions/vehicle.ts
  src/definitions/word.ts
  src/faker.ts
Labels: c: chore, p: 1-normal

#850 build!: remove node v12 support
  scripts/bundle.ts
Labels: p: 1-normal, s: accepted, c: refactor

#900 chore(deps): update pnpm to v7
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
Labels: c: dependencies

#847 build: add node v18 support
  .github/workflows/ci.yml
  netlify.toml
  package.json
  pnpm-lock.yaml
Labels: c: chore, p: 1-normal

#912 chore: remove obsolete DefinitionTypes type
  src/definitions/definitions.ts
  src/definitions/index.ts
  src/index.ts
Labels: c: chore, p: 1-normal, s: accepted

#913 chore(deps): add missing docs peer dependencies
  .github/renovate.json5
  package.json
  pnpm-lock.yaml
Labels: c: dependencies

#921 fix: empty array passed into helpers.arrayElements
  src/modules/helpers/index.ts
  test/helpers.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#916 refactor!: remove deprecations
  docs/.vitepress/api-pages.ts
  docs/guide/index.md
  src/faker.ts
  src/modules/datatype/index.ts
  src/modules/finance/index.ts
  src/modules/helpers/index.ts
  src/modules/name/index.ts
  src/modules/random/index.ts
  src/modules/time/index.ts
  src/modules/unique/index.ts
  test/datatype.spec.ts
  test/finance.spec.ts
  test/helpers.spec.ts
  test/name.spec.ts
  test/random.spec.ts
  test/time.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#848 refactor!: target es2020
  scripts/copyMimeTypes.ts
  tsconfig.json
  tsconfig.lint.json
Labels: p: 1-normal, s: accepted, c: refactor

#799 refactor!: remove faker default export
  src/index.ts
Labels: p: 1-normal, s: accepted, c: refactor

#908 test: ensure working examples and no console spam
  test/scripts/apidoc/.gitignore
  test/scripts/apidoc/examplesAndDeprecations.spec.ts
  test/scripts/apidoc/utils.ts
Labels: p: 1-normal, c: test

#925 fix: typo in error message
  src/modules/datatype/index.ts
  test/datatype.spec.ts
Labels: c: chore, p: 1-normal, s: accepted

#922 ci: check scripts
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  tsconfig.base.json
  tsconfig.check-scripts.json
  tsconfig.check-tests.json
  tsconfig.lint.json
Labels: c: chore, p: 1-normal, s: accepted

#884 feat: support locale definitions directly from faker.fake
  src/modules/fake/index.ts
  test/fake.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#937 docs: consistent capitalization of crypto methods
  src/modules/finance/index.ts
Labels: c: docs, p: 1-normal, s: accepted

#938 chore: fix lint warning in address module
  src/modules/address/index.ts
Labels: c: chore, p: 1-normal, s: accepted

#947 docs(docs/guide): Add typescript support in the guide
  docs/guide/index.md
Labels: c: docs, p: 1-normal, s: accepted

#934 chore: prettier ignore temp files
  .prettierignore
Labels: c: chore, p: 1-normal

#963 chore: fix emoji jsdocs formatting
  src/modules/internet/index.ts
Labels: c: docs, c: chore, p: 1-normal, s: accepted

#961 chore: ignore some lint warnings in tests
  test/all_functional.spec.ts
  test/fake.spec.ts
Labels: c: chore, p: 1-normal

#962 feat: add date.birthdate
  src/modules/date/index.ts
  test/date.spec.ts
Labels: c: feature, p: 1-normal

#957 chore: deprecate phone.phoneNumberFormat
  src/modules/phone/index.ts
Labels: c: chore, p: 1-normal

#958 chore: deprecate phone.phoneFormats
  src/modules/phone/index.ts
Labels: c: chore, p: 1-normal

#965 chore: generate consistent definition order for locales
  scripts/generateLocales.ts
  src/locales/ro/address/index.ts
Labels: c: chore, p: 1-normal

#945 feat(internet): HTTP random status code
  src/definitions/internet.ts
  src/locales/en/internet/http_status_code.ts
  src/locales/en/internet/index.ts
  src/modules/internet/index.ts
  test/internet.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#955 feat: add casing option
  src/modules/random/index.ts
  src/modules/vehicle/index.ts
  test/random.spec.ts
Labels: c: feature, p: 1-normal

#819 feat: allow banned as string
  src/modules/random/index.ts
  test/random.spec.ts
Labels: c: feature, p: 1-normal

#634 chore(ru-locale): renovate states/streets and domain suffix names
  src/locales/ru/address/city_name.ts
  src/locales/ru/address/state.ts
  src/locales/ru/address/street_name.ts
  src/locales/ru/address/street_suffix.ts
  src/locales/ru/internet/domain_suffix.ts
Labels: p: 1-normal, s: accepted, c: locale

#981 test: improve luhn checks (error messages only)
  test/finance.spec.ts
  test/helpers.spec.ts
Labels: p: 1-normal, c: test

#979 fix: type exports for module NodeNext, Node16
  package.json
Labels: c: bug, p: 1-normal

#791 feat: reimplement datatype.bigInt
  src/modules/datatype/index.ts
  test/datatype.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#986 feat: added sponsor and community members to the readme
  BACKERS.md
  README.md
Labels: c: chore, p: 1-normal, s: accepted

#839 docs: fix mersenne rand min max confusion
  src/modules/mersenne/index.ts
Labels: c: docs, p: 1-normal, s: accepted

#987 chore: link to older docs site
  docs/.vitepress/config.ts
  docs/.vitepress/tsconfig.json
  docs/.vitepress/versions.ts
Labels: c: docs, p: 1-normal, s: accepted

#988 chore(release): 7.0.0
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: c: release

#989 fix: revert type exports for module NodeNext, Node16 (#979)
  package.json
Labels: c: bug, p: 3-urgent, s: accepted

#990 chore(release): 7.0.1
  CHANGELOG.md
  package.json
Labels: c: release

#994 docs: small typo fix
  BACKERS.md
Labels: c: docs, p: 1-normal

#980 fix: Luhn generation algorithms and tests
  src/modules/helpers/index.ts
  src/modules/helpers/luhn-check.ts
  test/finance.spec.ts
  test/helpers.spec.ts
  test/phone.spec.ts
  test/support/luhnCheck.ts
Labels: c: bug, p: 1-normal, c: test

#996 feat: add music.songName
  src/definitions/music.ts
  src/locales/en/music/index.ts
  src/locales/en/music/song_name.ts
  src/modules/music/index.ts
  test/music.spec.ts
Labels: c: feature, p: 1-normal

#1005 fix(typescript): support module Node16/NodeNext
  package.json
Labels: c: bug, p: 1-normal, s: accepted

#1007 fix: 🇫🇷 fr and 🇨🇭 fr_CH 🎨 colors
  src/locales/en/music/index.ts
  src/locales/fr/color/human.ts
  src/locales/fr/color/index.ts
  src/locales/fr/commerce/index.ts
  src/locales/fr/index.ts
  src/locales/fr_CH/color/human.ts
  src/locales/fr_CH/color/index.ts
  src/locales/fr_CH/commerce/index.ts
  src/locales/fr_CH/index.ts
Labels: p: 1-normal, s: accepted, c: locale

#1013 chore: remove helpers.userCard() from README.md
  README.md
Labels: c: docs, p: 1-normal

#1019 ci: update to pnpm/action-setup@v2.2.2
  .github/workflows/ci.yml
Labels: p: 1-normal, c: dependencies, s: accepted

#1023 feat: add german adjectives
  src/locales/de/index.ts
  src/locales/de/word/adjective.ts
  src/locales/de/word/index.ts
  src/locales/de_AT/index.ts
  src/locales/de_AT/word/adjective.ts
  src/locales/de_AT/word/index.ts
Labels: p: 1-normal, s: accepted, c: locale
