Repository faker-js/faker, pull requests merged in 2022-02, with the labels that each got.

#381 fix: param can be optional
  src/name.ts
Labels: bug, p3-minor-bug :hammer:

#363 feat(types): provide strong typing for locales
  src/address.ts
  src/definitions.ts
  src/definitions/address.ts
  src/definitions/animal.ts
  src/definitions/commerce.ts
  src/definitions/company.ts
  src/definitions/database.ts
  src/definitions/date.ts
  src/definitions/definitions.ts
  src/definitions/finance.ts
  src/definitions/hacker.ts
  src/definitions/index.ts
  src/definitions/internet.ts
  src/definitions/lorem.ts
  src/definitions/music.ts
  src/definitions/name.ts
  src/definitions/phone_number.ts
  src/definitions/system.ts
  src/definitions/utils.ts
  src/definitions/vehicle.ts
  src/definitions/word.ts
  src/finance.ts
  src/index.ts
  src/locales/el/credit_card/index.ts
  src/locales/el/finance/index.ts
  src/locales/el/hacker/index.ts
  src/locales/en/address/index.ts
  src/locales/en/animal/index.ts
  src/locales/en/commerce/index.ts
  src/locales/en/company/index.ts
  src/locales/en/database/index.ts
  src/locales/en/date/index.ts
  src/locales/en/finance/credit_card/index.ts
  src/locales/en/finance/index.ts
  src/locales/en/hacker/index.ts
  src/locales/en/internet/index.ts
  src/locales/en/lorem/index.ts
  src/locales/en/music/index.ts
  src/locales/en/name/index.ts
  src/locales/en/name/title.ts
  src/locales/en/phone_number/index.ts
  src/locales/en/system/index.ts
  src/locales/en/vehicle/index.ts
  src/locales/en/word/index.ts
  src/locales/fa/finance/credit_card/index.ts
  src/locales/fa/finance/index.ts
  src/locales/nl/hacker/index.ts
  src/locales/ru/hacker/index.ts
  src/lorem.ts
  src/name.ts
Labels: documentation, enhancement

#386 test: rewrite hacker tests
  test/hacker.spec.ts
Labels: test

#390 docs: update music jsdocs
  src/music.ts
Labels: documentation, p1-chore :broom:

#392 ci: use cypress install binary flag
  .github/workflows/ci.yml
Labels: enhancement, p1-chore :broom:

#391 docs: update name jsdocs
  src/name.ts
Labels: documentation

#372 test: rewrite name tests
  test/name.spec.ts
Labels: test

#383 test: rewrite music tests
  test/music.spec.ts
Labels: test

#304 fix: removed dead code and adjusted fileExt
  src/system.ts
Labels: needs rebase, p2-nice-to-have :cake:

#338 chore: welcome only new issue creators
  .github/workflows/issue-labeling.yml
Labels: p1-chore :broom:

#337 chore: fix JSDoc comments in datatype.ts
  src/datatype.ts
Labels: documentation, p1-chore :broom:

#399 chore: remove eslint-plugin-prettier
  .eslintrc.js
  package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#397 chore: fix JSDoc comments in phone.ts
  src/phone.ts
Labels: documentation, p1-chore :broom:

#413 chore: StackBlitz playground
  README.md
  docs/.vitepress/config.mjs
  netlify.toml
Labels: documentation

#396 test: rewrite phone tests
  test/phone.spec.ts
Labels: test

#420 docs(fix): use named import
  docs/guide/index.md
Labels: documentation, duplicate

#418 chore: fix trailing commas in fish and state names
  src/locales/en/animal/fish.ts
  src/locales/en_ZA/address/state.ts
Labels: bug

#426 ci: configure codecov
  .github/.codecov.yml
  .github/workflows/ci.yml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  vite.config.ts
Labels: p1-chore :broom:, test

#431 fix: optional args on faker.finance.iban()
  src/finance.ts
Labels: bug

#400 chore: enable eslint-plugin-jsdoc
  .eslintrc.js
  package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:

#433 test: rewrite finance.spec.ts
  test/finance.spec.ts
Labels: test

#417 docs: add examples to animal jsdocs
  src/animal.ts
Labels: documentation

#432 test: cover source instead of bundled code
  src/address.ts
  src/finance.ts
  src/helpers.ts
  src/image.ts
  src/image_providers/lorempicsum.ts
  src/image_providers/lorempixel.ts
  src/image_providers/unsplash.ts
  src/internet.ts
  src/name.ts
  src/unique.ts
  test/address.spec.ts
  test/all_functional.spec.ts
  test/animal.spec.ts
  test/commerce.spec.ts
  test/company.spec.ts
  test/database.spec.ts
  test/datatype.spec.ts
  test/date.spec.ts
  test/fake.spec.ts
  test/finance.spec.ts
  test/finance_iban.spec.ts
  test/git.spec.ts
  test/hacker.spec.ts
  test/helpers.spec.ts
  test/image.spec.ts
  test/internet.spec.ts
  test/locales.spec.ts
  test/lorem.spec.ts
  test/music.spec.ts
  test/name.spec.ts
  test/phone.spec.ts
  test/random.spec.ts
  test/system.spec.ts
  test/time.spec.ts
  test/unique.spec.ts
  test/vehicle.spec.ts
  test/word.spec.ts
  vite.config.ts
Labels: test

#423 docs: improve company jsdocs
  src/company.ts
Labels: documentation

#424 docs: improve database jsdocs
  src/database.ts
Labels: documentation

#427 docs: improve date jsdocs
  src/date.ts
Labels: documentation

#406 docs: update fake jsdocs
  src/fake.ts
Labels: documentation

#434 docs: improve finance jsdocs
  src/definitions/finance.ts
  src/finance.ts
Labels: documentation

#437 docs: improve image jsdocs
  src/image.ts
Labels: documentation

#438 docs: improve mersenne jsdocs
  src/mersenne.ts
Labels: documentation

#435 docs: improve git jsdocs
  src/git.ts
Labels: documentation

#436 docs: improve hacker jsdocs
  src/hacker.ts
Labels: documentation

#439 docs: improve unique jsdocs
  src/unique.ts
Labels: documentation

#419 docs: scale the navbar logo up
  docs/.vitepress/theme/index.css
Labels: documentation

#445 ci: configure codecov threshold
  .github/.codecov.yml
Labels: p1-chore :broom:

#453 chore: revert 399
  .eslintrc.js
  package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:, dependencies

#454 fix(docs): faker.image.url should be under cloudflare ipfs
  README.md
Labels: documentation, p1-chore :broom:

#458 docs: improve lorem jsdocs
  src/lorem.ts
Labels: documentation

#421 test: rewrite time tests
  test/time.spec.ts
Labels: test

#403 chore: enable eslint cache
  package.json
Labels: p1-chore :broom:

#393 test: rewrite database tests
  test/database.spec.ts
Labels: test

#414 test: rewrite image tests
  test/image.spec.ts
Labels: test

#230 chore: add JSDoc comments to address.ts
  src/address.ts
Labels: documentation, p1-chore :broom:

#467 ci: clean eslintcache file
  package.json
Labels: enhancement

#442 docs: improve helpers jsdocs
  src/helpers.ts
Labels: documentation

#457 fix: fix unique method types
  src/unique.ts
  src/vendor/unique.ts
  test/unique.spec.ts
Labels: bug

#351 docs: fix JSDoc comments in commerce.ts
  src/commerce.ts
Labels: documentation, enhancement

#470 test: rewrite word
  test/word.spec.ts
Labels: test

#473 test: rewrite lorem
  test/lorem.spec.ts
Labels: test

#478 fix: handle missing or broken locales main index files
  scripts/generateLocales.ts
Labels: bug, p3-minor-bug :hammer:

#475 test: rewrite internet
  test/internet.spec.ts
  test/lorem.spec.ts
  test/support/times.ts
Labels: test

#489 docs: remove superfluous links in docs
  scripts/apidoc.ts
Labels: bug, documentation

#447 docs: improve internet jsdocs
  src/internet.ts
Labels: documentation

#469 test: rewrite vehicle
  test/vehicle.spec.ts
Labels: test

#490 test: rewrite random
  src/random.ts
  test/random.spec.ts
Labels: test

#488 fix: remove invalid aliases
  src/random.ts
Labels: bug

#493 test: rewrite company test
  test/company.spec.ts
Labels: test

#498 ci: group doc deps together
  .github/renovate.json5
Labels: documentation, enhancement, dependencies

#494 feat(types): generate all locales index files with non-any types
  scripts/generateLocales.ts
  src/locales/af_ZA/cell_phone/index.ts
  src/locales/ar/cell_phone/index.ts
  src/locales/ar/team/index.ts
  src/locales/de/cell_phone/index.ts
  src/locales/de_AT/cell_phone/index.ts
  src/locales/el/app/index.ts
  src/locales/el/business/index.ts
  src/locales/el/cell_phone/index.ts
  src/locales/el/finance/credit_card/index.ts
  src/locales/el/team/index.ts
  src/locales/en/app/index.ts
  src/locales/en/business/index.ts
  src/locales/en/cell_phone/index.ts
  src/locales/en/finance/credit_card/index.ts
  src/locales/en/team/index.ts
  src/locales/en_GB/cell_phone/index.ts
  src/locales/en_IE/cell_phone/index.ts
  src/locales/en_ZA/cell_phone/index.ts
  src/locales/es/cell_phone/index.ts
  src/locales/es_MX/cell_phone/index.ts
  src/locales/es_MX/team/index.ts
  src/locales/fa/cell_phone/index.ts
  src/locales/fa/finance/credit_card/index.ts
  src/locales/fr_BE/cell_phone/index.ts
  src/locales/ge/cell_phone/index.ts
  src/locales/he/cell_phone/index.ts
  src/locales/hr/cell_phone/index.ts
  src/locales/ja/cell_phone/index.ts
  src/locales/lv/cell_phone/index.ts
  src/locales/mk/cell_phone/index.ts
  src/locales/pl/cell_phone/index.ts
  src/locales/pt_PT/cell_phone/index.ts
  src/locales/ro/cell_phone/index.ts
  src/locales/sv/cell_phone/index.ts
  src/locales/sv/team/index.ts
  src/locales/tr/cell_phone/index.ts
  src/locales/ur/app/index.ts
  src/locales/ur/business/index.ts
  src/locales/ur/cell_phone/index.ts
  src/locales/ur/team/index.ts
  src/locales/vi/cell_phone/index.ts
  src/locales/zu_ZA/cell_phone/index.ts
Labels: enhancement

#499 test: rewrite helpers tests
  src/helpers.ts
  test/helpers.spec.ts
Labels: test

#512 chore: enable jsdoc/sort-tags
  .eslintrc.js
  src/address.ts
  src/company.ts
  src/date.ts
  src/finance.ts
  src/git.ts
  src/helpers.ts
  src/image_providers/lorempicsum.ts
  src/image_providers/lorempixel.ts
  src/image_providers/unsplash.ts
  src/name.ts
  src/random.ts
  src/word.ts
Labels: p1-chore :broom:

#515 test: rewrite finance iban
  test/finance_iban.spec.ts
Labels: test

#519 test: cleanup finance test
  test/finance.spec.ts
Labels: test

#517 fix: test random.alphaNumeric
  test/random.spec.ts
Labels: test

#520 build: add redirect aliases for cjs
  .gitignore
  package.json
  scripts/bundle.ts
Labels: p3-minor-bug :hammer:

#511 test: use toBeTypeOf
  test/address.spec.ts
  test/all_functional.spec.ts
  test/company.spec.ts
  test/database.spec.ts
  test/datatype.spec.ts
  test/finance.spec.ts
  test/git.spec.ts
  test/hacker.spec.ts
  test/helpers.spec.ts
  test/internet.spec.ts
  test/lorem.spec.ts
  test/mersenne.spec.ts
  test/music.spec.ts
  test/name.spec.ts
  test/random.spec.ts
  test/time.spec.ts
  test/unique.spec.ts
  test/vehicle.spec.ts
  test/word.spec.ts
Labels: p1-chore :broom:, test

#525 chore(deps): update devDependencies
  package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:, dependencies

#523 docs: various fixes
  src/datatype.ts
  src/date.ts
  src/finance.ts
  src/helpers.ts
  src/image.ts
  src/index.ts
  src/internet.ts
  src/lorem.ts
  src/mersenne.ts
  src/name.ts
  src/phone.ts
  src/random.ts
  src/time.ts
  src/word.ts
Labels: documentation

#446 docs: use vue components for api-docs
  docs/.vitepress/components/api-docs/method-parameters.vue
  docs/.vitepress/components/api-docs/method.ts
  docs/.vitepress/components/api-docs/method.vue
  docs/api/.gitignore
  package.json
  pnpm-lock.yaml
  scripts/apidoc.ts
  src/random.ts
Labels: documentation

#524 docs: show deprecation warnings in api docs
  docs/.vitepress/components/api-docs/method.ts
  docs/.vitepress/components/api-docs/method.vue
  scripts/apidoc.ts
Labels: documentation

#539 docs: Add prerequisite for typescript configuration
  README.md
Labels: documentation

#530 refactor: convert mersenne into a class
  src/mersenne.ts
  src/vendor/mersenne.ts
Labels: p1-chore :broom:

#529 fix: correcting the readme file
  README.md
Labels: documentation, p1-chore :broom:

#548 chore: move faker into own file
  scripts/generateLocales.ts
  src/faker.ts
  src/index.ts
  src/locale/af_ZA.ts
  src/locale/ar.ts
  src/locale/az.ts
  src/locale/cz.ts
  src/locale/de.ts
  src/locale/de_AT.ts
  src/locale/de_CH.ts
  src/locale/el.ts
  src/locale/en.ts
  src/locale/en_AU.ts
  src/locale/en_AU_ocker.ts
  src/locale/en_BORK.ts
  src/locale/en_CA.ts
  src/locale/en_GB.ts
  src/locale/en_GH.ts
  src/locale/en_IE.ts
  src/locale/en_IND.ts
  src/locale/en_NG.ts
  src/locale/en_US.ts
  src/locale/en_ZA.ts
  src/locale/es.ts
  src/locale/es_MX.ts
  src/locale/fa.ts
  src/locale/fi.ts
  src/locale/fr.ts
  src/locale/fr_BE.ts
  src/locale/fr_CA.ts
  src/locale/fr_CH.ts
  src/locale/ge.ts
  src/locale/he.ts
  src/locale/hr.ts
  src/locale/hy.ts
  src/locale/id_ID.ts
  src/locale/it.ts
  src/locale/ja.ts
  src/locale/ko.ts
  src/locale/lv.ts
  src/locale/mk.ts
  src/locale/nb_NO.ts
  src/locale/ne.ts
  src/locale/nl.ts
  src/locale/nl_BE.ts
  src/locale/pl.ts
  src/locale/pt_BR.ts
  src/locale/pt_PT.ts
  src/locale/ro.ts
  src/locale/ru.ts
  src/locale/sk.ts
  src/locale/sv.ts
  src/locale/tr.ts
  src/locale/uk.ts
  src/locale/ur.ts
  src/locale/vi.ts
  src/locale/zh_CN.ts
  src/locale/zh_TW.ts
  src/locale/zu_ZA.ts
  test/locale-imports.spec.ts
Labels: p4-important :exclamation:
