Repository faker-js/faker, pull requests merged in 2022-03, with the labels that each got.

#549 docs: rewrite tree-shaking part
  docs/migration-guide-v5/index.md
Labels: documentation

#552 chore(deps): add prettier-plugin-organize-imports
  .prettierrc.cjs
  docs/.vitepress/theme/components/index.mjs
  docs/.vitepress/theme/index.mjs
  package.json
  pnpm-lock.yaml
  scripts/verifyCommit.ts
  src/definitions/index.ts
  src/image.ts
  src/internet.ts
  src/locale/en_AU.ts
  src/locale/en_AU_ocker.ts
  src/locale/en_BORK.ts
  src/locale/en_CA.ts
  src/locale/en_GB.ts
  src/locale/en_GH.ts
  src/locale/en_IE.ts
  src/locale/en_IND.ts
  src/locale/en_NG.ts
  src/locale/en_US.ts
  src/locale/en_ZA.ts
  src/locale/es.ts
  src/locale/es_MX.ts
  src/locale/fa.ts
  src/locale/fi.ts
  src/locale/fr.ts
  src/locale/fr_BE.ts
  src/locale/fr_CA.ts
  src/locale/fr_CH.ts
  src/locale/ge.ts
  src/locale/he.ts
  src/locale/hr.ts
  src/locale/hy.ts
  src/locale/id_ID.ts
  src/locale/it.ts
  src/locale/ja.ts
  src/locale/ko.ts
  src/locale/lv.ts
  src/locale/mk.ts
  src/locale/nb_NO.ts
  src/locale/ne.ts
  src/locale/nl.ts
  src/locale/nl_BE.ts
  src/locale/pl.ts
  src/locale/pt_BR.ts
  src/locale/pt_PT.ts
  src/locale/ro.ts
  src/locale/ru.ts
  src/locale/sk.ts
  src/locale/sv.ts
  src/locale/tr.ts
  src/locale/uk.ts
  src/locale/ur.ts
  src/locale/vi.ts
  src/locale/zh_CN.ts
  src/locale/zh_TW.ts
  src/locale/zu_ZA.ts
  src/unique.ts
  test/system.spec.ts
Labels: p1-chore :broom:, dependencies

#566 chore: refactor datatype array function
  src/datatype.ts
Labels: enhancement, p1-chore :broom:

#567 chore(type): type seedValue
  src/datatype.ts
  src/faker.ts
  src/random.ts
  test/address.spec.ts
  test/animal.spec.ts
  test/commerce.spec.ts
  test/company.spec.ts
  test/database.spec.ts
  test/datatype.spec.ts
  test/date.spec.ts
  test/finance.spec.ts
  test/finance_iban.spec.ts
  test/git.spec.ts
  test/hacker.spec.ts
  test/helpers.spec.ts
  test/internet.spec.ts
  test/lorem.spec.ts
  test/music.spec.ts
  test/name.spec.ts
  test/phone.spec.ts
  test/system.spec.ts
  test/time.spec.ts
  test/unique.spec.ts
  test/vehicle.spec.ts
  test/word.spec.ts
Labels: p1-chore :broom:

#565 docs: Fix 'Missing' entries
  src/helpers.ts
  src/vehicle.ts
Labels: documentation

#564 docs: generate docs for fake() and unique()
  docs/api/.gitignore
  docs/api/fake.md
  scripts/apidoc.ts
  scripts/apidoc/apiDocsWriter.ts
  scripts/apidoc/directMethods.ts
  scripts/apidoc/moduleMethods.ts
  scripts/apidoc/signature.ts
  scripts/apidoc/utils.ts
  src/fake.ts
  src/unique.ts
Labels: documentation

#562 docs: improve random jsdocs (part 2)
  src/random.ts
Labels: documentation

#571 docs: add toc and hide edit link
  scripts/apidoc/apiDocsWriter.ts
Labels: documentation

#584 chore(deps): update deps
  package.json
  pnpm-lock.yaml
Labels: dependencies

#586 fix: fix time.recent method signature
  src/faker.ts
  src/time.ts
Labels: bug

#570 docs: document options params in api docs
  scripts/apidoc/signature.ts
Labels: documentation

#602 docs: show union options parameters
  scripts/apidoc/signature.ts
Labels: documentation, enhancement

#583 ci: improve renovate config
  .github/renovate.json5
Labels: dependencies

#596 docs: display correct signature
  scripts/apidoc/directMethods.ts
  scripts/apidoc/moduleMethods.ts
  src/random.ts
Labels: documentation, enhancement

#574 docs: add test for api docs generation
  test/scripts/apidoc/.gitignore
  test/scripts/apidoc/signature.example.ts
  test/scripts/apidoc/signature.expected.json
  test/scripts/apidoc/signature.spec.ts
  test/scripts/apidoc/tsconfig.json
Labels: documentation, test

#599 docs: comment out algolia until search is available
  docs/.vitepress/config.mjs
Labels: documentation, p1-chore :broom:

#597 chore: fix eslint error
  test/address.spec.ts
Labels: p1-chore :broom:

#595 chore: configure eqeqeq lint rule
  .eslintrc.js
  pnpm-lock.yaml
  src/datatype.ts
  src/date.ts
  src/finance.ts
  src/helpers.ts
  src/internet.ts
  src/lorem.ts
  src/mersenne.ts
  src/vendor/mersenne.ts
  src/word.ts
  test/address.spec.ts
  test/finance.spec.ts
Labels: p1-chore :broom:

#608 docs: improve visualization for complex types
  scripts/apidoc/signature.ts
  src/unique.ts
  test/scripts/apidoc/signature.example.ts
  test/scripts/apidoc/signature.expected.json
Labels: documentation

#612 docs: add image_providers jsdocs
  src/image_providers/lorempicsum.ts
  src/image_providers/lorempixel.ts
  src/image_providers/unsplash.ts
Labels: documentation

#621 chore: update automated labels
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/renovate.json5
Labels: c: chore, p: 2-high

#633 docs: fix prisis github profile link
  docs/update.md
Labels: c: docs, p: 1-normal

#168 fix(finance): update iso-3166-1 country codes for IBAN/BIC
  src/iban.ts
  test/finance.spec.ts
Labels: c: bug, p: 1-normal

#543 chore: deprecate helpers.*Card methods
  README.md
  src/helpers.ts
  test/helpers.spec.ts
Labels: p: 1-normal, c: refactor

#506 docs: deprecate randomize
  src/helpers.ts
  test/helpers.spec.ts
Labels: c: docs, p: 1-normal, s: accepted, c: refactor

#577 fix: mersenne rand invalid input argument
  src/mersenne.ts
  test/mersenne.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#508 fix: remove unreachable code finance
  src/finance.ts
Labels: p: 1-normal, s: accepted, c: refactor

#440 chore(locale): added curated names for default(en) locale
  src/locales/en/name/female_middle_name.ts
  src/locales/en/name/index.ts
  src/locales/en/name/male_middle_name.ts
  src/locales/en/name/middle_name.ts
  test/name.spec.ts
Labels: c: bug, p: 1-normal, s: accepted, c: locale

#636 docs: add alternative CDN links
  README.md
  docs/guide/index.md
Labels: c: docs, p: 1-normal, s: accepted

#651 chore: partially activate strict mode
  tsconfig.json
Labels: c: chore, p: 1-normal

#647 ci: configure codecov patch threshold
  .github/.codecov.yml
Labels: c: chore, p: 2-high, s: accepted

#659 docs: fix page meta
  docs/.vitepress/config.mjs
Labels: c: bug, c: docs, p: 2-high

#641 fix: enable algolia search
  docs/.vitepress/config.mjs
Labels: c: docs, p: 2-high, s: accepted

#646 fix: corrected the Costa Rican IBAN format
  src/iban.ts
  test/finance_iban.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#657 docs: extract defaults from the comments if absent otherwise
  scripts/apidoc/signature.ts
Labels: c: docs, p: 1-normal, s: accepted

#663 ci: reduce diff coverage target
  .github/.codecov.yml
Labels: c: chore, p: 2-high, s: accepted

#275 chore: drop fake usage in vehicle.ts
  src/vehicle.ts
Labels: c: chore, p: 1-normal, s: accepted

#200 fix: accept dates as params for Date methods
  src/date.ts
  src/helpers.ts
  test/date.spec.ts
Labels: c: bug, p: 1-normal

#662 fix: normalize provider in finance.creditCardNumber
  src/finance.ts
  test/finance.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#347 fix: fake is unable to return empty strings
  src/fake.ts
  test/fake.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#343 fix: datatype.datetime should use static boundaries
  src/datatype.ts
  test/datatype.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#563 refactor: set seed directly
  src/datatype.ts
  src/faker.ts
  src/random.ts
  test/faker.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#649 fix: solve various todos
  src/address.ts
  src/faker.ts
  src/internet.ts
  src/lorem.ts
Labels: p: 1-normal, s: accepted, c: refactor

#644 fix: name module gender
  src/index.ts
  src/name.ts
  test/helpers.spec.ts
  test/name.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#654 fix: only return word with desirable alpha characters
  src/random.ts
  test/random.spec.ts
  test/system.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#669 test: remove todo for number conversion
  test/commerce.spec.ts
  test/finance.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#670 refactor: date accept number input
  src/date.ts
  test/date.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#658 docs: convert to typescript
  docs/.vitepress/.gitignore
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/index.ts
  docs/.vitepress/theme/components/vue.d.ts
  docs/.vitepress/theme/index.ts
  scripts/apidoc/apiDocsWriter.ts
Labels: c: docs, p: 1-normal, s: accepted

#661 refactor: deprecate time.recent
  src/time.ts
  test/time.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#650 refactor: use smart eqeqeq null checks
  scripts/apidoc/signature.ts
  scripts/generateLocales.ts
  src/address.ts
  src/datatype.ts
  src/date.ts
  src/fake.ts
  src/faker.ts
  src/finance.ts
  src/helpers.ts
  src/image.ts
  src/image_providers/lorempixel.ts
  src/image_providers/unsplash.ts
  src/internet.ts
  src/lorem.ts
  src/random.ts
  src/vendor/unique.ts
  test/finance.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#668 refactor: use number tuple as input for coordinate
  src/address.ts
Labels: p: 1-normal, s: accepted, c: refactor

#666 docs: remove api methods section
  README.md
Labels: c: docs, p: 1-normal, s: accepted

#667 test: fix flaky unique test coverage
  test/unique.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#680 refactor(address.secondaryAddress): use local definition
  src/address.ts
Labels: c: bug, p: 1-normal

#687 refactor: replace intern use of helper.randomize
  src/finance.ts
  src/helpers.ts
Labels: c: chore, p: 1-normal, s: accepted

#678 chore: replace substr with substring
  src/fake.ts
Labels: c: chore, p: 1-normal, s: accepted

#692 fix: replaced placeimg.com on loremflickr.com
  src/image.ts
Labels: c: bug, p: 1-normal, s: accepted

#701 docs: mention template literals in fake docs
  src/fake.ts
Labels: c: docs, p: 1-normal

#703 refactor: drop usage of `fake` for internal calls
  src/git.ts
  src/lorem.ts
  src/random.ts
  src/system.ts
Labels: p: 1-normal, s: accepted, c: refactor

#609 test: fix all_functional tests
  test/all_functional.spec.ts
Labels: c: bug, p: 2-high, c: test

#580 fix: force passed locales into faker constructor
  src/faker.ts
  test/faker.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#697 fix: use require/import export map in package.json
  package.json
  scripts/bundle.ts
Labels: p: 1-normal, s: accepted, c: refactor

#689 chore: use a standardized deprecated function
  src/helpers.ts
  src/internal/deprecated.ts
  src/name.ts
  src/random.ts
  src/time.ts
  test/helpers.spec.ts
  test/name.spec.ts
  test/random.spec.ts
  test/time.spec.ts
  tsconfig.json
Labels: c: chore, p: 1-normal, s: accepted

#320 fix: Vehicle vin is always 17 characters long
  src/vehicle.ts
  test/vehicle.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#688 fix: fake behavior with special replacement patterns
  src/fake.ts
  test/fake.spec.ts
Labels: c: bug, p: 1-normal

#708 release: 6.1.0
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: p: 1-normal, c: release, s: accepted

#716 release: 6.1.1
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: p: 3-urgent, c: release, s: accepted

#709 docs: update faker.fake documentation
  src/fake.ts
Labels: c: docs, p: 1-normal, s: accepted

#727 docs: fix lint warning
  scripts/apidoc/parameterDefaults.ts
Labels: c: docs, p: 1-normal

#719 docs: add ts import example in readme
  README.md
Labels: c: docs, p: 1-normal, s: accepted

#740 docs: Use valid UUID for example in README
  README.md
Labels: c: docs, p: 1-normal, s: accepted

#739 test: added a few test cases for Albania IBAN
  test/finance_iban.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#738 chore: move vendor to utils and update license notes
  LICENSE
  src/internet.ts
  src/mersenne.ts
  src/unique.ts
  src/utils/mersenne.ts
  src/utils/unique.ts
  src/utils/user-agent.ts
  src/vendor/mersenne.ts
Labels: c: docs, c: chore, p: 1-normal

#664 fix: datatype.number when min = max + precision, throw when max > min
  src/address.ts
  src/datatype.ts
  src/random.ts
  test/address.spec.ts
  test/datatype.spec.ts
  test/system.spec.ts
  test/word.spec.ts
Labels: c: bug, p: 1-normal, s: accepted

#673 docs: about
  docs/.vitepress/config.ts
  docs/about/announcements.md
  docs/about/announcements/2022-01-14.md
  docs/about/team.md
  docs/about/team/TeamMember.ts
  docs/about/team/TeamMember.vue
  docs/about/team/TeamPage.vue
  docs/about/team/members.json
  netlify.toml
Labels: c: docs, p: 1-normal, s: accepted

#718 feat: FakerError
  src/errors/faker-error.ts
  src/fake.ts
  src/faker.ts
  src/finance.ts
  src/index.ts
  src/mersenne.ts
  src/random.ts
  src/utils/unique.ts
  test/fake.spec.ts
  test/faker.spec.ts
  test/finance.spec.ts
  test/mersenne.spec.ts
  test/unique.spec.ts
Labels: c: feature, p: 1-normal, s: accepted
