Repository faker-js/faker, pull requests merged in 2022-01, with the labels that each got.

#27 chore: remove reference to faker cloud
  Readme.md
Labels: p1-chore :broom:

#39 chore: commit package-lock.json
  .gitignore
  package-lock.json
Labels: p1-chore :broom:

#35 feat(github): add github actions
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#12 fix(tests): fix failing tests
  lib/datatype.js
  lib/finance.js
  test/finance.unit.js
  test/random.unit.js
Labels: bug, p3-minor-bug :hammer:, test

#41 chore(ci): automated issue labeling
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/freestyle.md
  .github/workflows/issue-labeling.yml
Labels: p1-chore :broom:

#32 chore: remove code of merit
  CODE_OF_MERIT.MD
Labels: p1-chore :broom:

#40 chore: add prettier
  .editorconfig
  .prettierignore
  .prettierrc.cjs
  .vscode/extensions.json
  package-lock.json
  package.json
Labels: p1-chore :broom:

#61 docs: rename to faker
  Readme.md
Labels: p1-chore :broom:

#57 docs: add code of conduct from Contributor Covenant
  CODE_OF_CONDUCT.md
Labels: p1-chore :broom:

#58 docs: remove stale badges from README and add discord badge
  Readme.md
Labels: p1-chore :broom:

#65 chore: format .github
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/freestyle.md
  .github/workflows/ci.yml
  .github/workflows/issue-labeling.yml
Labels: p1-chore :broom:

#62 chore: prettier ignore examples browser js
  .prettierignore
Labels: p1-chore :broom:

#64 chore: format root files
  .eslintrc
  .prettierignore
  CHANGELOG_old.md
  CONTRIBUTING.md
  README.md
  conf.json
  gulpfile.js
  index.js
Labels: p1-chore :broom:

#30 feat: update sponsors, backers references
  README.md
Labels: p1-chore :broom:

#84 feat: add definitions
  src/index.ts
Labels: p2-nice-to-have :cake:

#59 chore: add Github actions status badge
  README.md
Labels: p1-chore :broom:

#68 chore(ci): add commit automation
  .github/semantic.yml
  package-lock.json
  package.json
  scripts/verifyCommit.ts
Labels: p1-chore :broom:

#93 docs: add installation instructions to top of README
  README.md
Labels: documentation, p4-important :exclamation:

#95 fix(#28): changed fakercloud url to cloudflare-ipfs.com
  lib/internet.js
  test/image.unit.js
Labels: p5-urgent :fire:

#63 chore: remove invalid closed html tag
  examples/browser/index.html
Labels: p1-chore :broom:

#110 chore: swap funding to be sent through the open collective
  .github/FUNDING.yml
  package.json
Labels: enhancement

#67 chore: format tests
  test/address.unit.js
  test/all.functional.js
  test/animal.unit.js
  test/browser.unit.html
  test/commerce.unit.js
  test/company.unit.js
  test/database.unit.js
  test/datatype.unit.js
  test/date.unit.js
  test/fake.unit.js
  test/finance.unit.js
  test/finance_iban.unit.js
  test/git.unit.js
  test/helpers.unit.js
  test/internet.unit.js
  test/locales.unit.js
  test/lorem.unit.js
  test/music.unit.js
  test/name.unit.js
  test/phone_number.unit.js
  test/random.unit.js
  test/run.js
  test/support/chai.js
  test/support/function-helpers.js
  test/support/luhnCheck.js
  test/support/sinon-1.5.2.js
  test/support/walk_dir.js
  test/system.unit.js
  test/time.unit.js
  test/unique.unit.js
  test/vehicle.unit.js
  test/word.unit.js
Labels: p1-chore :broom:, test

#83 feat: migrate date
  src/date.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#81 feat: migrate hacker
  src/hacker.ts
  src/helpers.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#78 feat: migrate git
  src/git.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#79 feat: migrate fake
  src/fake.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#103 feat: migrate name
  src/index.ts
  src/name.ts
Labels: p2-nice-to-have :cake:

#74 feat: migrate time
  src/index.ts
  src/time.ts
Labels: p2-nice-to-have :cake:

#94 feat: migrate internet
  src/index.ts
  src/internet.ts
Labels: p2-nice-to-have :cake:

#92 feat: migrate image
  src/image.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#89 feat: migrate database
  src/database.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#90 feat: migrate system
  src/index.ts
  src/system.ts
Labels: p2-nice-to-have :cake:

#102 feat: migrate word
  src/index.ts
  src/word.ts
Labels: p2-nice-to-have :cake:

#105 feat: migrate animal
  src/animal.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#106 feat: migrate commerce
  src/commerce.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#127 feat: migrate phone
  src/index.ts
  src/phone_number.ts
Labels: p2-nice-to-have :cake:

#107 feat: migrate music
  src/index.ts
  src/music.ts
Labels: p2-nice-to-have :cake:

#86 feat: migrate lorem
  src/index.ts
  src/lorem.ts
Labels: p2-nice-to-have :cake:

#131 feat: migrate finance
  src/finance.ts
  src/iban.ts
  src/index.ts
  test/finance.unit.js
  test/finance_iban.unit.js
Labels: p2-nice-to-have :cake:

#133 feat: migrate address
  src/address.ts
  src/fake.ts
  src/helpers.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#132 feat: migrate company
  src/company.ts
  src/index.ts
Labels: p2-nice-to-have :cake:

#130 feat: migrate vehicle
  src/index.ts
  src/vehicle.ts
Labels: p2-nice-to-have :cake:

#143 chore: update .npmignore to prevent unwanted code in the package dist
  .npmignore
Labels: p4-important :exclamation:

#147 chore: fixup package name in package.json
  package-lock.json
  package.json
Labels: p5-urgent :fire:

#148 fix: added missing keys into package.json
  package.json
Labels: p2-nice-to-have :cake:

#150 chore: sorted package.json
  package.json
Labels: p1-chore :broom:

#137 feat(domain_suffix): add missing domain for id_ID
  lib/locales/id_ID/internet/domain_suffix.js
Labels: p2-nice-to-have :cake:

#140 feat: Updated meta tags for rich text preview
  docs/.vitepress/config.mjs
Labels: documentation

#138 docs: an update from the faker team
  docs/.vitepress/config.mjs
  docs/guide/recent-faqs.md
  docs/public/first-week-wins.png
  docs/update.md
Labels: documentation

#173 chore: add files field in package.json
  .npmignore
  package.json
Labels: p4-important :exclamation:

#157 chore: update license
  LICENSE
Labels: p4-important :exclamation:

#180 fix: typo in update.md
  docs/update.md
Labels: documentation, p1-chore :broom:

#163 docs: add yarn and pnpm install commands
  README.md
  docs/guide/index.md
Labels: documentation, p1-chore :broom:

#195 chore: support dark mode for favicon
  docs/public/logo.svg
Labels: p2-nice-to-have :cake:

#154 chore(docs): fix imports
  README.md
  doc/index.html
  doc/quicksearch.html
  docs/api/localization.md
  docs/guide/index.md
Labels: documentation, p1-chore :broom:

#178 chore: migrate image providers to TS
  .gitignore
  lib/image_providers/lorempicsum.js
  lib/image_providers/lorempixel.js
  lib/image_providers/unsplash.js
  src/image.ts
  src/image_providers/lorempicsum.ts
  src/image_providers/lorempixel.ts
  src/image_providers/unsplash.ts
Labels: p1-chore :broom:

#183 refactor: Use datatype.number() function instead of random.number()
  src/internet.ts
Labels: p2-nice-to-have :cake:

#204 chore: add commit conventions doc
  .github/commit-convention.md
Labels: documentation, p1-chore :broom:

#152 feat!: support tree-shaking
  build/gulp-tasks/browser.js
  examples/node/generateMultiLevelMultiLocaleJSON.js
  examples/node/generateSet.js
  examples/node/generators.js
  examples/node/minimal-usage.js
  examples/node/unique-values.js
  index.d.ts
  index.js
  index.ts
  package.json
  src/index.ts
  test/address.unit.js
  test/all.functional.js
  test/animal.unit.js
  test/commerce.unit.js
  test/company.unit.js
  test/database.unit.js
  test/datatype.unit.js
  test/date.unit.js
  test/fake.unit.js
  test/finance.unit.js
  test/finance_iban.unit.js
  test/git.unit.js
  test/helpers.unit.js
  test/image.unit.js
  test/internet.unit.js
  test/locales.unit.js
  test/lorem.unit.js
  test/music.unit.js
  test/name.unit.js
  test/phone_number.unit.js
  test/random.unit.js
  test/support/function-helpers.js
  test/system.unit.js
  test/time.unit.js
  test/unique.unit.js
  test/vehicle.unit.js
  test/word.unit.js
Labels: needs test, p2-nice-to-have :cake:

#205 docs: adding new logo
  README.md
  docs/.vitepress/config.mjs
  docs/index.md
  docs/public/logo.svg
  docs/public/social-image.png
Labels: documentation, p2-nice-to-have :cake:

#179 ci: add node version matrix
  .github/workflows/ci.yml
  package-lock.json
  package.json
  test/finance.unit.js
Labels: p4-important :exclamation:

#158 chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: p4-important :exclamation:

#153 chore: switch to pnpm
  .github/workflows/ci.yml
  .gitignore
  .npm/package/.gitignore
  .npm/package/README
  .npm/package/npm-shrinkwrap.json
  .prettierignore
  netlify.toml
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:, dependencies

#160 docs(readme.md): api methods table with description
  README.md
Labels: documentation, p1-chore :broom:

#189 chore: add support for readonly arrays
  src/helpers.ts
  src/random.ts
Labels: p3-minor-bug :hammer:

#161 docs(readme.md): add repository badges
  README.md
Labels: documentation, p1-chore :broom:

#231 docs: shorten TLDR; move to the permalink instead
  .github/commit-convention.md
Labels: documentation, p1-chore :broom:

#227 docs: add c# port to list
  docs/update.md
Labels: documentation, p1-chore :broom:

#249 feat: use export default for locales
  src/index.ts
  src/locales/index.ts
Labels: p1-chore :broom:

#250 chore: add JSDoc comments to animal.ts
  src/animal.ts
Labels: documentation, p1-chore :broom:

#255 docs: minor capitalization fix
  README.md
Labels: documentation, p1-chore :broom:

#259 fix: jalapeño typo
  src/locales/en/word/noun.ts
Labels: p1-chore :broom:

#262 chore(test): Add locale to test description
  test/all_functional.spec.ts
Labels: test

#248 feat: add autocomplete support for locales
  src/index.ts
  src/locales/index.ts
Labels: p2-nice-to-have :cake:

#263 fix: add missing fakers for existing locales
  src/locale/fr_BE.ts
  src/locale/lv.ts
Labels: p3-minor-bug :hammer:

#271 test: fix suppressed warnings
  test/name.spec.ts
Labels: p1-chore :broom:

#264 docs: update locale list/table in docs
  README.md
  docs/api/localization.md
Labels: documentation

#278 chore(docs): Typo in README
  README.md
Labels: documentation, p1-chore :broom:

#254 chore: migrate vendor
  package.json
  src/internet.ts
  src/mersenne.ts
  src/unique.ts
  src/vendor/mersenne.ts
  src/vendor/unique.ts
  src/vendor/user-agent.ts
Labels: p4-important :exclamation:

#257 build: bundle with esbuild
  .eslintignore
  .prettierignore
  CONTRIBUTING.md
  README.md
  build/gulp-tasks/browser.js
  docs/.vitepress/theme/components/Playground.vue
  docs/guide/index.md
  gulpfile.js
  package.json
  pnpm-lock.yaml
  scripts/bundle.ts
  src/iban.ts
  src/locale/fr_BE.ts
  src/locale/lv.ts
  test/address.spec.ts
  test/all_functional.spec.ts
  test/animal.spec.ts
  test/commerce.spec.ts
  test/company.spec.ts
  test/database.spec.ts
  test/datatype.spec.ts
  test/date.spec.ts
  test/fake.spec.ts
  test/finance.spec.ts
  test/finance_iban.spec.ts
  test/git.spec.ts
  test/helpers.spec.ts
  test/image.spec.ts
  test/internet.spec.ts
  test/locales.spec.ts
  test/lorem.spec.ts
  test/music.spec.ts
  test/name.spec.ts
  test/phone_number.spec.ts
  test/random.spec.ts
  test/system.spec.ts
  test/time.spec.ts
  test/unique.spec.ts
  test/vehicle.spec.ts
  test/word.spec.ts
  tsconfig.json
Labels: p1-chore :broom:

#273 chore: fix JSDoc comments in word.ts
  src/word.ts
Labels: p1-chore :broom:

#288 chore: fix JSDoc comments in time.ts
  src/time.ts
Labels: documentation, p1-chore :broom:

#292 chore: ignore some more files
  .eslintignore
  .gitignore
Labels: p1-chore :broom:

#251 docs: readme cleanup
  README.md
  src/random.ts
  test/random.spec.ts
Labels: documentation, p1-chore :broom:

#267 chore: add .nvmrc for those who use automatic node switching
  .nvmrc
Labels: p1-chore :broom:

#284 chore: change TODO owner name
  src/address.ts
  src/helpers.ts
  src/internet.ts
Labels: p1-chore :broom:

#298 chore: fix JSDoc comments in system.ts
  src/system.ts
Labels: documentation, p1-chore :broom:

#274 chore: fix JSDoc comments in vehicle.ts
  src/vehicle.ts
Labels: documentation, p1-chore :broom:

#297 test: add test for locale imports
  test/locale-imports.spec.ts
Labels: test

#293 test: improve animal tests
  test/animal.spec.ts
Labels: test

#294 test: rewrite commerce tests
  test/commerce.spec.ts
Labels: test

#282 docs: provide migration guide
  docs/.vitepress/config.mjs
  docs/migration/index.md
Labels: documentation

#301 docs: provide migration guide (round 2!)
  README.md
  docs/.vitepress/config.mjs
  docs/guide/index.md
  docs/migration-guide-v5/index.md
Labels: documentation

#289 docs: automatically generate api docs from source
  .gitignore
  docs/.vitepress/.gitignore
  docs/.vitepress/config.mjs
  docs/api/.gitignore
  docs/api/address.md
  docs/api/commerce.md
  docs/api/company.md
  docs/api/database.md
  docs/api/datatype.md
  docs/api/date.md
  docs/api/finance.md
  docs/api/hacker.md
  docs/api/helpers.md
  docs/api/image.md
  docs/api/internet.md
  package.json
  pnpm-lock.yaml
  scripts/apidoc.ts
Labels: documentation

#323 fix: fake docs not accessible
  scripts/apidoc.ts
Labels: bug, documentation

#326 fix: docs v-pre issue
  scripts/apidoc.ts
Labels: bug, documentation

#325 build: add clean command
  package.json
Labels: enhancement

#318 test: use run for coverage
  package.json
Labels: p1-chore :broom:, test

#315 chore: replace var
  src/datatype.ts
  src/helpers.ts
  src/name.ts
  src/word.ts
Labels: p1-chore :broom:

#311 chore: configure .vscode
  .vscode/extensions.json
  .vscode/settings.json
Labels: p1-chore :broom:

#317 ci: check formatting
  .github/workflows/ci.yml
Labels: p1-chore :broom:

#307 fix: some return types
  src/database.ts
  src/finance.ts
  src/hacker.ts
Labels: p1-chore :broom:

#306 feat: add chat.fakerjs.dev subdomain redirection to discord
  .github/ISSUE_TEMPLATE/config.yml
  CODE_OF_CONDUCT.md
  README.md
  docs/guide/index.md
  docs/update.md
  netlify.toml
Labels: p2-nice-to-have :cake:

#299 chore: add missing type on the system.commonFileName method
  src/system.ts
Labels: p1-chore :broom:

#240 chore: adding cypress integration tests
  .github/workflows/ci.yml
  cypress.json
  cypress/e2e/smoke.cy.ts
  cypress/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: p2-nice-to-have :cake:, test

#330 docs: use html tables instead of md tables to account for ::: v-pre
  docs/.vitepress/theme/index.css
  docs/.vitepress/theme/index.mjs
  scripts/apidoc.ts
Labels: documentation

#316 chore(deps): update some devDependencies
  package.json
  pnpm-lock.yaml
Labels: p1-chore :broom:, dependencies

#151 chore: setup improved linting
  .eslintignore
  .eslintrc
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  scripts/apidoc.ts
  scripts/verifyCommit.ts
  src/helpers.ts
  src/internet.ts
  src/locales/ar/name/last_name.ts
  src/name.ts
  src/unique.ts
  src/vendor/unique.ts
  src/vendor/user-agent.ts
  src/word.ts
  test/animal.spec.ts
  test/commerce.spec.ts
  test/random.spec.ts
  tsconfig.lint.json
Labels: p1-chore :broom:

#342 chore: add discord link to fakerjs.dev navbar
  docs/.vitepress/config.mjs
Labels: documentation, p2-nice-to-have :cake:

#358 chore: add more type annotations
  src/address.ts
  src/animal.ts
  src/date.ts
  src/finance.ts
  src/helpers.ts
  src/internet.ts
  src/lorem.ts
  src/random.ts
  src/system.ts
Labels: p2-nice-to-have :cake:

#340 chore: rename phone_number to phone
  src/index.ts
  src/phone.ts
  test/phone.spec.ts
Labels: p1-chore :broom:

#362 feat: add more arabic names dataset
  src/locales/ar/name/female_first_name.ts
  src/locales/ar/name/index.ts
  src/locales/ar/name/male_first_name.ts
  src/locales/ar/name/suffix.ts
Labels: enhancement, p2-nice-to-have :cake:

#357 fix: use ban-types recommended
  .eslintrc.js
  src/fake.ts
Labels: p1-chore :broom:

#341 fix: removing toc to fix the docs html
  .gitignore
  cypress.json
  cypress/e2e/smoke.cy.ts
  scripts/apidoc.ts
Labels: bug, documentation, test

#360 chore: use recommended no-var-requires
  .eslintrc.js
  test/finance.spec.ts
  test/finance_iban.spec.ts
  test/locale-imports.spec.ts
Labels: p1-chore :broom:

#285 test: remove mocks from address
  test/address.spec.ts
Labels: test

#361 chore: use explicit-module-boundary-types
  .eslintrc.js
  src/address.ts
  src/helpers.ts
  src/iban.ts
  src/image_providers/unsplash.ts
  src/internet.ts
  src/lorem.ts
  src/mersenne.ts
  src/phone.ts
  src/random.ts
  src/vendor/user-agent.ts
Labels: p1-chore :broom:

#369 chore: use recommended restrict-plus-operands
  .eslintrc.js
  scripts/apidoc.ts
  src/commerce.ts
  src/finance.ts
  src/image.ts
  src/image_providers/lorempicsum.ts
  src/image_providers/lorempixel.ts
  src/image_providers/unsplash.ts
  src/internet.ts
  src/lorem.ts
  src/vehicle.ts
  src/vendor/mersenne.ts
  src/vendor/unique.ts
  src/vendor/user-agent.ts
  test/database.spec.ts
  test/finance.spec.ts
  test/finance_iban.spec.ts
Labels: p1-chore :broom:

#258 fix: improve internet tests and fix bug in domain name generation
  package.json
  pnpm-lock.yaml
  src/internet.ts
  test/internet.spec.ts
Labels: p3-minor-bug :hammer:, test

#312 test: rewrite date tests
  test/date.spec.ts
Labels: test

#335 fix: remove redundant precision from datatype.datetime options
  src/datatype.ts
Labels: bug, p1-chore :broom:

#370 test: rewrite unique tests
  test/unique.spec.ts
Labels: test

#346 chore(docs): reduce console spam and trim examples from code
  scripts/apidoc.ts
Labels: p1-chore :broom:

#303 test: remove mocks from system
  test/system.spec.ts
Labels: test
