Repository faker-js/faker, pull requests merged in 2022-06, with the labels that each got.

#1027 chore: remove superfluous newline from generate:locales script
  scripts/generateLocales.ts
Labels: c: chore, p: 1-normal, s: accepted

#1035 docs: fix faker.datatype.number document
  src/modules/datatype/index.ts
Labels: c: docs

#1034 feat: always use https for loremflickr
  src/modules/image/index.ts
Labels: c: feature, p: 1-normal, s: accepted

#1014 feat: science module
  docs/.vitepress/api-pages.ts
  scripts/generateLocales.ts
  src/definitions/definitions.ts
  src/definitions/index.ts
  src/definitions/science.ts
  src/faker.ts
  src/index.ts
  src/locales/en/index.ts
  src/locales/en/science/chemicalElement.ts
  src/locales/en/science/index.ts
  src/locales/en/science/unit.ts
  src/modules/science/index.ts
  test/science.spec.ts
Labels: c: feature, p: 1-normal

#1017 docs: rework readme
  CONTRIBUTING.md
  README.md
Labels: c: docs, p: 1-normal, s: accepted

#1039 docs: add science module to readme
  README.md
Labels: c: docs, p: 1-normal

#1042 feat: improve norwegian translations
  src/locales/nb_NO/color/human.ts
  src/locales/nb_NO/color/index.ts
  src/locales/nb_NO/commerce/department.ts
  src/locales/nb_NO/commerce/index.ts
  src/locales/nb_NO/index.ts
  src/locales/nb_NO/science/chemicalElement.ts
  src/locales/nb_NO/science/index.ts
  src/locales/nb_NO/science/unit.ts
  src/locales/nb_NO/word/adjective.ts
  src/locales/nb_NO/word/conjunction.ts
  src/locales/nb_NO/word/index.ts
  src/locales/nb_NO/word/interjection.ts
Labels: p: 1-normal, s: accepted, c: locale

#1041 chore: deprecate cityPrefix and citySuffix
  src/locales/af_ZA/address/city.ts
  src/locales/el/address/city.ts
  src/locales/en_AU/address/city.ts
  src/locales/en_CA/address/city.ts
  src/locales/en_GB/address/city.ts
  src/locales/en_IE/address/city.ts
  src/locales/en_US/address/city.ts
  src/locales/fr_CA/address/city.ts
  src/locales/ne/address/city.ts
  src/locales/pt_BR/address/city.ts
  src/locales/ro/address/city.ts
  src/locales/tr/address/city.ts
  src/locales/zu_ZA/address/city.ts
  src/modules/address/index.ts
Labels: c: chore, p: 1-normal

#1045 test: improve internet tests
  test/internet.spec.ts
Labels: c: test

#1065 chore(lorempicsum.avatar): deprecate
  src/modules/image/providers/lorempicsum.ts
Labels: c: chore, p: 1-normal, s: accepted

#1062 chore(unsplash.avatar): deprecate
  src/modules/image/providers/unsplash.ts
Labels: c: chore, p: 1-normal, s: accepted

#1069 chore(lorempixel.avatar): deprecate
  src/modules/image/providers/lorempixel.ts
Labels: c: chore, p: 1-normal, s: accepted

#1063 refactor(phone): rename phoneNumber to number
  src/modules/fake/index.ts
  src/modules/phone/index.ts
  test/fake.spec.ts
  test/phone.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#1046 chore(unsplash): deprecate unused const
  src/modules/image/providers/unsplash.ts
Labels: c: chore, p: 1-normal, s: accepted

#1067 docs: deprecation workflow
  CONTRIBUTING.md
  src/internal/deprecated.ts
  src/modules/address/index.ts
  src/modules/commerce/index.ts
  src/modules/phone/index.ts
  src/modules/random/index.ts
Labels: c: docs, c: chore, p: 1-normal, s: accepted

#1085 fix: lower target to support Webpack 4
  scripts/bundle.ts
  tsconfig.json
Labels: c: bug, p: 1-normal, s: accepted

#1089 chore(random.alpha): remove todo comment
  src/modules/random/index.ts
Labels: c: chore, p: 1-normal, s: accepted

#1055 chore: renovate pl locales
  src/locales/pl/address/building_number.ts
  src/locales/pl/address/city_name.ts
  src/locales/pl/address/country.ts
  src/locales/pl/address/secondary_address.ts
  src/locales/pl/address/state.ts
  src/locales/pl/address/state_abbr.ts
  src/locales/pl/color/human.ts
  src/locales/pl/color/index.ts
  src/locales/pl/company/adjective.ts
  src/locales/pl/company/index.ts
  src/locales/pl/company/suffix.ts
  src/locales/pl/index.ts
  src/locales/pl/music/genre.ts
  src/locales/pl/music/index.ts
  src/locales/pl/music/song_name.ts
  src/locales/pl/science/chemicalElement.ts
  src/locales/pl/science/index.ts
  src/locales/pl/science/unit.ts
  src/locales/pl/team/index.ts
  src/locales/pl/team/name.ts
  src/locales/pl/team/prefix.ts
Labels: p: 1-normal, s: accepted, c: locale

#1080 refactor(name.findName): allow prefix and suffix
  src/modules/name/index.ts
  test/name.spec.ts
Labels: p: 1-normal, s: accepted, c: refactor

#959 docs: add hint that the generated data might be real ones
  README.md
Labels: c: docs, p: 1-normal, s: needs decision

#875 test: migrate datatype to test snapshots
  test/__snapshots__/address.spec.ts.snap
  test/__snapshots__/animal.spec.ts.snap
  test/__snapshots__/color.spec.ts.snap
  test/__snapshots__/commerce.spec.ts.snap
  test/__snapshots__/company.spec.ts.snap
  test/__snapshots__/database.spec.ts.snap
  test/__snapshots__/datatype.spec.ts.snap
  test/__snapshots__/date.spec.ts.snap
  test/__snapshots__/finance.spec.ts.snap
  test/__snapshots__/git.spec.ts.snap
  test/__snapshots__/hacker.spec.ts.snap
  test/__snapshots__/helpers.spec.ts.snap
  test/__snapshots__/internet.spec.ts.snap
  test/__snapshots__/lorem.spec.ts.snap
  test/__snapshots__/mersenne.spec.ts.snap
  test/__snapshots__/music.spec.ts.snap
  test/__snapshots__/name.spec.ts.snap
  test/__snapshots__/phone.spec.ts.snap
  test/__snapshots__/random.spec.ts.snap
  test/__snapshots__/science.spec.ts.snap
  test/__snapshots__/system.spec.ts.snap
  test/__snapshots__/unique.spec.ts.snap
  test/__snapshots__/vehicle.spec.ts.snap
  test/__snapshots__/word.spec.ts.snap
  test/address.spec.ts
  test/animal.spec.ts
  test/color.spec.ts
  test/commerce.spec.ts
  test/company.spec.ts
  test/database.spec.ts
  test/datatype.spec.ts
  test/date.spec.ts
  test/finance.spec.ts
  test/git.spec.ts
  test/hacker.spec.ts
  test/helpers.spec.ts
  test/internet.spec.ts
  test/lorem.spec.ts
  test/mersenne.spec.ts
  test/music.spec.ts
  test/name.spec.ts
  test/phone.spec.ts
  test/random.spec.ts
  test/science.spec.ts
  test/support/seededRuns.ts
  test/system.spec.ts
  test/unique.spec.ts
  test/vehicle.spec.ts
  test/word.spec.ts
Labels: p: 1-normal, c: test, s: accepted

#1086 feat: add abbreviations to `hacker.abbreviation()` in the `en` locale
  src/locales/en/hacker/abbreviation.ts
  test/__snapshots__/hacker.spec.ts.snap
Labels: p: 1-normal, c: locale

#1093 chore: use type export for science interfaces
  src/index.ts
Labels: c: chore

#1095 chore(release): 7.3.0
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: p: 1-normal, c: release

#1088 test: fix cypress doc tests
  cypress.config.ts
  cypress.json
Labels: p: 1-normal, c: test, s: accepted

#1104 docs(contributing): jsdocs section
  CONTRIBUTING.md
Labels: c: docs, p: 1-normal

#1115 chore: testing unpredictable emails and usernames
  test/internet.spec.ts
Labels: c: test
