Repository faker-js/faker, pull requests merged in 2023-10, with the labels that each got.

#2284 feat: support custom randomizer
  docs/.vitepress/api-pages.ts
  docs/.vitepress/config.ts
  docs/guide/randomizer.md
  scripts/apidoc/fakerClass.ts
  scripts/apidoc/generate.ts
  src/faker.ts
  src/index.ts
  src/internal/mersenne.ts
  src/internal/mersenne/mersenne.ts
  src/modules/number/index.ts
  src/randomizer.ts
  src/simple-faker.ts
  test/all_functional.spec.ts
  test/faker.spec.ts
  test/mersenne.spec.ts
Labels: c: feature, p: 1-normal

#2371 feat(locale): add street_name to `en_US`, `en_GB` and `en`
  src/locales/en/location/index.ts
  src/locales/en/location/street_name.ts
  src/locales/en/location/street_pattern.ts
  src/locales/en_GB/location/index.ts
  src/locales/en_GB/location/street_name.ts
  src/locales/en_GB/location/street_pattern.ts
  src/locales/en_US/location/index.ts
  src/locales/en_US/location/street_name.ts
  src/locales/en_US/location/street_pattern.ts
  test/all_functional.spec.ts
  test/modules/__snapshots__/location.spec.ts.snap
  test/modules/__snapshots__/random.spec.ts.snap
Labels: c: feature, p: 1-normal, c: locale, m: location

#2431 chore: randomizer cleanup
  src/internal/mersenne.ts
  src/simple-faker.ts
  test/__snapshots__/mersenne.spec.ts.snap
  test/mersenne.spec.ts
Labels: c: chore, p: 1-normal

#2418 infra(deps): add eslint unicorn
  .eslintrc.js
  package.json
  pnpm-lock.yaml
Labels: c: dependencies, s: accepted, c: infra

#2420 infra(unicorn): prefer-node-protocol
  .eslintrc.js
  scripts/apidoc/generate.ts
Labels: p: 1-normal, c: infra

#2419 infra(unicorn): prefer-date-now
  .eslintrc.js
  src/modules/helpers/index.ts
  src/modules/helpers/unique.ts
  test/modules/helpers.spec.ts
Labels: p: 1-normal, c: infra

#2433 docs: fix outdated comment regarding multiple faker locales
  README.md
Labels: c: docs, p: 1-normal

#2434 infra: enable no-useless-escape eslint rule
  .eslintrc.js
  scripts/generateLocales.ts
  src/modules/git/index.ts
  src/modules/helpers/index.ts
  src/modules/internet/index.ts
  test/modules/commerce.spec.ts
  test/modules/finance.spec.ts
  test/modules/helpers.spec.ts
  test/modules/image.spec.ts
  test/modules/internet.spec.ts
  test/scripts/apidoc/verify-jsdoc-tags.spec.ts
Labels: p: 1-normal, c: infra

#2438 chore: fix iban test typos
  test/modules/finance_iban.spec.ts
Labels: c: chore, p: 1-normal

#2447 infra(unicorn): no-console-spaces
  .eslintrc.js
  test/scripts/apidoc/signature.debug.ts
Labels: p: 1-normal, c: infra

#2446 infra(unicorn): prefer-array-flat-map
  .eslintrc.js
  scripts/apidoc/diff.ts
  src/locales/th/person/last_name.ts
Labels: p: 1-normal, c: infra

#2443 infra(unicorn): prefer-object-from-entries
  .eslintrc.js
  scripts/apidoc/apiDocsWriter.ts
  scripts/apidoc/generate.ts
  scripts/apidoc/utils.ts
Labels: p: 1-normal, c: infra

#2442 infra(unicorn): prefer-string-starts-ends-with
  .eslintrc.js
  scripts/apidoc/signature.ts
Labels: p: 1-normal, c: infra

#2441 infra(unicorn): no-new-array
  .eslintrc.js
  src/internal/mersenne.ts
Labels: p: 1-normal, c: infra

#2436 docs: improve wording regarding locale selection
  README.md
  docs/index.md
Labels: c: docs, p: 1-normal

#2448 infra(unicorn): use hashbang for scripts
  .eslintrc.js
  scripts/apidoc.ts
  scripts/bundle.ts
  scripts/diff.ts
  scripts/generateLocales.ts
Labels: p: 1-normal, c: infra

#2454 infra(unicorn): no-array-push-push
  .eslintrc.js
  scripts/generateLocales.ts
  src/modules/helpers/index.ts
Labels: p: 1-normal, c: infra

#2455 infra(unicorn): explicit-length-check
  .eslintrc.js
  scripts/apidoc/signature.ts
  test/all_functional.spec.ts
  test/vitest-extensions.ts
Labels: p: 1-normal, c: infra

#2461 infra(unicorn): no-array-for-each
  .eslintrc.js
  scripts/apidoc/parameterDefaults.ts
  src/modules/datatype/index.ts
  src/modules/system/index.ts
  test/all_functional.spec.ts
  test/modules/color.spec.ts
  test/modules/helpers.spec.ts
  test/modules/system.spec.ts
  test/scripts/apidoc/signature.debug.ts
  test/scripts/apidoc/verify-jsdoc-tags.spec.ts
Labels: p: 1-normal, c: infra

#2463 infra(unicorn): prefer-includes
  .eslintrc.js
  src/modules/helpers/index.ts
  src/modules/helpers/unique.ts
  test/all_functional.spec.ts
Labels: p: 1-normal, c: infra

#2462 infra(unicorn): consistent-destructuring
  .eslintrc.js
  src/modules/helpers/unique.ts
Labels: p: 1-normal, c: infra

#2475 docs: fix bad Promise usage
  scripts/apidoc/generate.ts
  scripts/apidoc/signature.ts
  test/scripts/apidoc/__snapshots__/signature.spec.ts.snap
  test/scripts/apidoc/signature.debug.ts
  test/scripts/apidoc/signature.example.ts
Labels: c: bug, c: docs, p: 2-high

#2471 infra(unicorn): catch-error-name
  .eslintrc.js
  scripts/generateLocales.ts
  src/modules/helpers/index.ts
Labels: p: 1-normal, c: infra

#2474 docs(number): improve documentation regarding number bounds
  src/modules/number/index.ts
Labels: c: docs, p: 1-normal, m: number

#2478 chore(release): 8.2.0
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: p: 2-high, c: release

#2421 infra(unicorn): prefer-spread
  .eslintrc.js
  src/internal/merge.ts
  src/modules/color/index.ts
  src/modules/company/index.ts
  src/modules/finance/index.ts
  src/modules/helpers/index.ts
  src/modules/internet/index.ts
  src/modules/string/index.ts
  src/modules/system/index.ts
  test/modules/datatype.spec.ts
  test/modules/helpers.spec.ts
  test/modules/number.spec.ts
  test/modules/random.spec.ts
  test/modules/string.spec.ts
  test/modules/system.spec.ts
  test/support/seededRuns.ts
Labels: p: 1-normal, s: accepted, c: infra

#2466 infra(typescript-eslint): prefer-regexp-exec
  .eslintrc.js
  src/modules/helpers/index.ts
  test/modules/airline.spec.ts
Labels: p: 1-normal, c: infra

#2459 infra(unicorn): no-instanceof-array
  .eslintrc.js
Labels: p: 1-normal, c: infra

#2469 infra(unicorn): escape-case
  .eslintrc.js
  src/modules/git/index.ts
  src/modules/helpers/index.ts
  src/modules/internet/index.ts
Labels: p: 1-normal, c: infra

#2265 infra: implement inactive locales content generation enhancement
  scripts/generateLocales.ts
Labels: p: 1-normal, c: locale, c: infra

#2486 docs: fix deprecated text for internet.password
  src/modules/internet/index.ts
Labels: c: docs, p: 1-normal

#2452 infra(unicorn): prefer-number-properties
  .eslintrc.js
  src/modules/commerce/index.ts
  src/modules/date/index.ts
  src/modules/helpers/index.ts
  src/modules/helpers/luhn-check.ts
  test/modules/number.spec.ts
Labels: p: 1-normal, c: infra

#2453 infra(unicorn): no-zero-fractions
  .eslintrc.js
Labels: p: 1-normal, c: infra

#2491 infra(unicorn): prefer-optional-catch-binding
  .eslintrc.js
Labels: p: 1-normal, c: infra

#2496 chore: substrings of length one
  scripts/apidoc/typedoc.ts
  src/modules/helpers/luhn-check.ts
Labels: c: chore, p: 1-normal

#2495 refactor(finance): simplify litecoin address implementation
  src/modules/finance/index.ts
Labels: p: 1-normal, c: refactor, m: finance

#2445 infra(unicorn): prefer-native-coercion-functions
  .eslintrc.js
  scripts/apidoc/typedoc.ts
Labels: p: 1-normal, c: infra

#2502 docs: fix typo in usage.md
  docs/guide/usage.md
Labels: c: docs, p: 1-normal, s: accepted

#2490 infra(unicorn): no-for-loop
  .eslintrc.js
  src/modules/finance/iban.ts
  test/docs/versions.spec.ts
Labels: p: 1-normal, c: infra

#2468 infra(eslint): config cleanup
  .eslintrc.js
Labels: p: 1-normal, c: infra

#2451 infra(unicorn): prefer-array-some
  .eslintrc.js
Labels: p: 1-normal, s: accepted, c: infra

#2464 infra(unicorn): prefer-ternary
  .eslintrc.js
  src/modules/date/index.ts
  src/modules/finance/index.ts
  src/modules/internet/index.ts
Labels: p: 1-normal, c: infra

#2492 infra(unicorn): filename-case
  .eslintrc.js
  package.json
  scripts/apidoc/faker-class.ts
  scripts/apidoc/faker-utilities.ts
  scripts/apidoc/generate.ts
  scripts/apidoc/module-methods.ts
  scripts/apidoc/parameter-defaults.ts
  scripts/apidoc/typedoc.ts
  scripts/apidoc/writer.ts
  scripts/generate-locales.ts
  src/modules/lorem/index.ts
  src/modules/word/filter-word-list-by-length.ts
  src/modules/word/index.ts
  test/all-functional.spec.ts
  test/mersenne.spec.ts
  test/modules/airline.spec.ts
  test/modules/animal.spec.ts
  test/modules/color.spec.ts
  test/modules/commerce.spec.ts
  test/modules/company.spec.ts
  test/modules/database.spec.ts
  test/modules/datatype.spec.ts
  test/modules/date.spec.ts
  test/modules/finance-iban.spec.ts
  test/modules/finance.spec.ts
  test/modules/git.spec.ts
  test/modules/hacker.spec.ts
  test/modules/helpers.spec.ts
  test/modules/image.spec.ts
  test/modules/internet.spec.ts
  test/modules/location.spec.ts
  test/modules/lorem.spec.ts
  test/modules/music.spec.ts
  test/modules/number.spec.ts
  test/modules/person.spec.ts
  test/modules/phone.spec.ts
  test/modules/random.spec.ts
  test/modules/science.spec.ts
  test/modules/string.spec.ts
  test/modules/system.spec.ts
  test/modules/vehicle.spec.ts
  test/modules/word.spec.ts
  test/scripts/apidoc/module.spec.ts
  test/support/seeded-runs.ts
Labels: p: 1-normal, c: infra

#2493 refactor(finance): simplify maskedNumber implementation
  src/modules/finance/index.ts
Labels: p: 1-normal, c: refactor, m: finance

#2511 infra(unicorn): prefer-top-level-await
  .eslintrc.js
Labels: p: 1-normal, c: infra

#2517 docs(phone): improve deprecation and see message
  src/modules/phone/index.ts
Labels: c: docs, p: 1-normal, m: phone
