Repository faker-js/faker, pull requests merged in 2024-02, with the labels that each got.

#2630 docs: fix missing or invalid jsdocs
  src/faker.ts
  src/modules/location/index.ts
  src/simple-faker.ts
Labels: c: docs, p: 1-normal

#2637 docs(utilities): add missing since
  src/randomizer.ts
  src/utils/merge-locales.ts
Labels: c: docs, p: 1-normal

#2632 docs: override default vitepress brand colors
  docs/.vitepress/theme/index.css
Labels: c: docs, p: 1-normal, c: infra

#2646 chore(release): v8.4.1
  CHANGELOG.md
  package.json
Labels: p: 1-normal, c: release

#2121 infra!: drop NodeJS v14 and v16 support
  .github/workflows/ci.yml
  docs/guide/upgrading_v9/2121.md
  package.json
  pnpm-lock.yaml
  scripts/bundle.ts
  tsconfig.build.json
  vitest.config.ts
Labels: p: 1-normal, c: dependencies, breaking change, c: infra

#2590 chore(deps): replace vitest v1 deprecations
  test/faker.spec.ts
  test/simple-faker.spec.ts
Labels: p: 1-normal, c: dependencies

#2657 docs: update README to indicate next.fakerjs.dev will be v9
  README.md
Labels: c: docs, p: 1-normal

#2658 infra: use text eol=lf
  .gitattributes
Labels: p: 1-normal, c: infra

#2484 feat(food): new module
  docs/.vitepress/api-pages.ts
  scripts/generate-locales.ts
  src/definitions/definitions.ts
  src/definitions/food.ts
  src/definitions/index.ts
  src/faker.ts
  src/index.ts
  src/locales/en/food/adjective.ts
  src/locales/en/food/description_pattern.ts
  src/locales/en/food/dish.ts
  src/locales/en/food/dish_pattern.ts
  src/locales/en/food/ethnic_category.ts
  src/locales/en/food/fruit.ts
  src/locales/en/food/index.ts
  src/locales/en/food/ingredient.ts
  src/locales/en/food/meat.ts
  src/locales/en/food/spice.ts
  src/locales/en/food/vegetable.ts
  src/locales/en/index.ts
  src/modules/food/index.ts
  test/modules/__snapshots__/food.spec.ts.snap
  test/modules/food.spec.ts
Labels: c: feature, p: 1-normal, s: accepted, m: food

#2660 docs(finance): fix bad see tags
  src/modules/finance/index.ts
Labels: c: docs, p: 1-normal, m: finance

#2659 docs(system): fix bad description
  src/modules/system/index.ts
Labels: c: docs, p: 1-normal, m: system

#2472 refactor(image)!: randomize defaults
  docs/guide/upgrading_v9/2472.md
  src/modules/image/index.ts
  test/modules/__snapshots__/image.spec.ts.snap
  test/modules/image.spec.ts
Labels: c: feature, p: 1-normal, breaking change, m: image

#2665 docs: create stub for v9 migration guide
  docs/.vitepress/config.ts
  docs/guide/upgrading.md
Labels: c: docs

#2391 chore!: switch to tsup
  CONTRIBUTING.md
  docs/guide/upgrading_v9/2391.md
  package.json
  pnpm-lock.yaml
  scripts/bundle.ts
  test/locale-imports.spec.ts
  tsup.config.ts
Labels: c: chore, p: 1-normal, c: dependencies, breaking change, c: infra

#2401 esm with tsup demonstration
  test/locale-imports.spec.ts
Labels: do NOT merge yet

#2261 chore: convert to esm
  .eslintrc.cjs
  .github/workflows/ci.yml
  .github/workflows/commentCodeGeneration.ts
  .github/workflows/pr.yml
  .prettierrc.js
  package.json
  test/faker.spec.ts
  test/locale-imports.spec.ts
Labels: c: chore, p: 1-normal

#2653 infra(unicorn): prefer-string-replace-all
  .eslintrc.cjs
  docs/guide/upgrading_v9/2653.md
  scripts/apidoc/markdown.ts
  scripts/apidoc/utils.ts
  scripts/apidoc/writer.ts
  scripts/generate-locales.ts
  src/modules/color/index.ts
  src/modules/finance/iban.ts
  src/modules/finance/index.ts
  src/modules/git/index.ts
  src/modules/helpers/index.ts
  src/modules/helpers/luhn-check.ts
  src/modules/internet/index.ts
  src/modules/location/index.ts
  src/modules/string/index.ts
  src/modules/system/index.ts
  test/modules/finance.spec.ts
  test/modules/system.spec.ts
  test/scripts/apidoc/verify-jsdoc-tags.spec.ts
Labels: p: 1-normal, breaking change, c: infra

#2654 infra(unicorn): prefer-at
  .eslintrc.cjs
  docs/guide/upgrading_v9/2654.md
  scripts/apidoc/parameter-defaults.ts
  scripts/apidoc/typedoc.ts
  scripts/generate-locales.ts
  src/modules/helpers/index.ts
  test/modules/color.spec.ts
  test/modules/date.spec.ts
  test/modules/lorem.spec.ts
  test/modules/system.spec.ts
Labels: p: 1-normal, breaking change, c: infra

#2668 docs: more jsdoc fixes
  src/faker.ts
  src/modules/finance/index.ts
  src/modules/helpers/index.ts
  src/modules/internet/index.ts
  src/modules/location/index.ts
  src/randomizer.ts
  src/utils/merge-locales.ts
Labels: c: docs, p: 1-normal

#2508 infra(unicorn): no-useless-switch-case
  .eslintrc.cjs
  docs/guide/upgrading_v9/2508.md
  src/modules/color/index.ts
  src/modules/internet/index.ts
  src/modules/location/index.ts
  src/modules/string/index.ts
  test/modules/__snapshots__/git.spec.ts.snap
  test/modules/__snapshots__/internet.spec.ts.snap
Labels: p: 1-normal, s: accepted, breaking change, c: infra

#2676 infra: don't remove pnpm-lock on clean
  package.json
Labels: p: 1-normal, c: infra

#2677 infra(renovate): enable lockFileMaintenance
  .github/renovate.json5
Labels: p: 1-normal, c: dependencies, c: infra

#2684 infra(ci): highlight preflight diff errors in github
  .github/workflows/pr.yml
Labels: p: 1-normal, c: infra

#2682 refactor!: remove v8 deprecated faker class stuff
  docs/guide/upgrading_v9/2682.md
  src/faker.ts
Labels: p: 1-normal, breaking change

#2678 refactor(random)!: remove v8 deprecated random module
  docs/.vitepress/api-pages.ts
  docs/guide/upgrading_v9/2678.md
  src/faker.ts
  src/index.ts
  src/modules/random/index.ts
  test/all-functional.spec.ts
  test/modules/helpers.spec.ts
  test/modules/random.spec.ts
Labels: p: 1-normal, c: refactor, breaking change, m: random

#2685 feat(helpers)!: use const generics where possible
  docs/guide/upgrading_v9/2685.md
  package.json
  src/modules/helpers/index.ts
  test/modules/helpers.spec-d.ts
  vitest.config.ts
Labels: c: feature, p: 1-normal, breaking change

#2683 infra(vitest): enable github-actions-reporter
  .github/workflows/pr.yml
  vitest.config.ts
Labels: p: 1-normal, c: infra

#2680 infra(unicorn): prefer-top-level-await
  .eslintrc.cjs
  scripts/apidoc.ts
  scripts/diff.ts
  scripts/generate-locales.ts
  test/scripts/apidoc/signature.debug.ts
Labels: p: 1-normal, c: infra

#2694 refactor(datatype)!: remove v8 deprecated datatype methods
  docs/guide/upgrading_v9/2694.md
  src/faker.ts
  src/modules/datatype/index.ts
  test/modules/__snapshots__/datatype.spec.ts.snap
  test/modules/__snapshots__/helpers.spec.ts.snap
  test/modules/datatype.spec.ts
  test/modules/helpers.spec.ts
Labels: p: 1-normal, c: refactor, m: datatype

#2357 feat!: high precision random number generator
  docs/guide/randomizer.md
  docs/guide/upgrading_v9/2357.md
  src/faker.ts
  src/index.ts
  src/internal/mersenne.ts
  src/simple-faker.ts
  test/internal/__snapshots__/mersenne.spec.ts.snap
  test/internal/mersenne.spec.ts
  test/modules/__snapshots__/airline.spec.ts.snap
  test/modules/__snapshots__/color.spec.ts.snap
  test/modules/__snapshots__/commerce.spec.ts.snap
  test/modules/__snapshots__/company.spec.ts.snap
  test/modules/__snapshots__/database.spec.ts.snap
  test/modules/__snapshots__/datatype.spec.ts.snap
  test/modules/__snapshots__/date.spec.ts.snap
  test/modules/__snapshots__/finance.spec.ts.snap
  test/modules/__snapshots__/food.spec.ts.snap
  test/modules/__snapshots__/git.spec.ts.snap
  test/modules/__snapshots__/hacker.spec.ts.snap
  test/modules/__snapshots__/helpers.spec.ts.snap
  test/modules/__snapshots__/image.spec.ts.snap
  test/modules/__snapshots__/internet.spec.ts.snap
  test/modules/__snapshots__/location.spec.ts.snap
  test/modules/__snapshots__/lorem.spec.ts.snap
  test/modules/__snapshots__/number.spec.ts.snap
  test/modules/__snapshots__/person.spec.ts.snap
  test/modules/__snapshots__/phone.spec.ts.snap
  test/modules/__snapshots__/random.spec.ts.snap
  test/modules/__snapshots__/string.spec.ts.snap
  test/modules/__snapshots__/system.spec.ts.snap
  test/modules/__snapshots__/vehicle.spec.ts.snap
  test/modules/__snapshots__/word.spec.ts.snap
  test/modules/date.spec.ts
  test/modules/helpers.spec.ts
  test/simple-faker.spec.ts
Labels: c: bug, p: 1-normal, breaking change, m: number

#2696 docs: fix unsupported nested css
  docs/.vitepress/theme/index.css
Labels: c: docs, p: 1-normal

#2697 refactor(random)!: remove v8 deprecated image methods
  docs/guide/upgrading_v9/2697.md
  src/modules/image/index.ts
  test/modules/image.spec.ts
Labels: p: 1-normal, c: refactor
