Repository faker-js/faker, pull requests merged in 2024-07, with the labels that each got.

#2989 chore: remove unused function mergeArrays
  scripts/generate-locales.ts
  src/internal/merge.ts
Labels: c: chore, p: 1-normal

#2988 infra(release): check release PR
  .github/workflows/check-release-pr.yml
Labels: p: 1-normal, c: infra

#2990 infra(release): draft release
  .github/workflows/draft-release.yml
Labels: p: 1-normal, c: infra

#2981 infra(release): prepare release PR
  .github/workflows/prepare-release-pr.yml
Labels: p: 1-normal, c: infra

#3003 chore(deps): update eslint plugins
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
Labels: c: chore, p: 1-normal, c: dependencies

#2991 infra(release): publish release
  .github/workflows/publish-release.yml
Labels: p: 1-normal, c: infra

#3018 docs: replace deprecated moduleResolution
  docs/guide/usage.md
Labels: c: docs, p: 1-normal

#3029 infra(release): use PAT for releases
  .github/workflows/prepare-release-pr.yml
  .github/workflows/publish-release.yml
Labels: p: 1-normal, c: infra
