Repository faker-js/faker, pull requests merged in 2024-09, with the labels that each got.

#3096 infra: improve package.json fields
  package.json
Labels: p: 1-normal, c: infra

#3098 infra: sort package.json automatically
  .prettierrc.js
  package.json
  pnpm-lock.yaml
Labels: p: 1-normal, c: infra

#3091 infra: remove redirect from current stable
  netlify.toml
Labels: c: bug, c: docs, p: 2-high, c: infra

#3092 infra(netlify): remove ignore script
  netlify.toml
Labels: c: docs, p: 1-normal, c: infra

#3082 infra: improve error messages for parameter properties
  scripts/apidocs/processing/error.ts
  scripts/apidocs/processing/jsdocs.ts
  scripts/apidocs/processing/parameter.ts
  scripts/apidocs/utils/value-checks.ts
  scripts/env.ts
  vitest.config.ts
Labels: p: 1-normal, c: infra

#3081 chore: improve nullish-checks in tests
  test/all-functional.spec.ts
  test/support/seeded-runs.ts
Labels: c: chore, p: 1-normal

#3093 fix: emit cts types
  .github/workflows/ci.yml
  CONTRIBUTING.md
  package.json
  scripts/apidocs/project.ts
  test/faker.spec.ts
  tsconfig.build.json
  tsconfig.json
  tsup.config.ts
Labels: c: bug, p: 2-high, c: infra

#3080 refactor(location): adjust zipCode nullish checks
  src/modules/location/index.ts
Labels: p: 1-normal, c: refactor, m: location

#3044 infra: use eslint.config.ts
  .vscode/settings.json
  eslint.config.ts
  package.json
  pnpm-lock.yaml
Labels: p: 1-normal, c: infra

#3120 docs: consistent linking to sponsored services
  README.md
Labels: c: docs, p: 1-normal

#3020 fix(locale): correction of pt_PT location and person data
  src/locales/pt_PT/location/country.ts
  src/locales/pt_PT/location/secondary_address.ts
  src/locales/pt_PT/location/state.ts
  src/locales/pt_PT/person/last_name.ts
  src/locales/pt_PT/person/prefix.ts
Labels: p: 1-normal, c: locale, m: location, m: person

#3090 docs: use defineProps deconstruction
  docs/.vitepress/components/Banner.vue
  docs/.vitepress/components/api-docs/method-parameters.vue
  docs/.vitepress/components/api-docs/method.vue
Labels: c: docs, p: 1-normal

#3119 infra: publish releases with provenance
  .github/workflows/publish-release.yml
Labels: p: 1-normal, c: infra

#3109 refactor(image): deprecate avatarLegacy for removal
  src/modules/image/index.ts
  test/modules/__snapshots__/image.spec.ts.snap
  test/modules/image.spec.ts
Labels: p: 1-normal, c: refactor, m: image, deprecation

#3125 docs: fix definition names in 'Company Name Affix files reorganized' section of migration guide
  docs/guide/upgrading.md
Labels: c: docs, p: 1-normal

#3124 chore: fix avatarLegacy deprecation version typo
  src/modules/image/index.ts
Labels: c: chore, p: 1-normal, m: image

#3141 infra: update file structure for util/internal
  src/faker.ts
  src/index.ts
  src/internal/locale-proxy.ts
  src/internal/mersenne.ts
  src/internal/types.ts
  src/modules/date/index.ts
  src/modules/string/index.ts
  src/simple-faker.ts
  src/utils/mersenne.ts
  test/internal/locale-proxy.spec.ts
  test/modules/number.spec.ts
  test/scripts/apidocs/method.example.ts
  test/scripts/apidocs/verify-jsdoc-tags.spec.ts
  test/support/seeded-runs.ts
  test/utils/__snapshots__/mersenne.spec.ts.snap
  test/utils/mersenne-test-utils.ts
  test/utils/mersenne.spec.ts
Labels: p: 1-normal, c: infra

#3142 refactor(locale): Update list of french legal entity
  src/locales/fr/company/legal_entity_type.ts
Labels: p: 1-normal, c: refactor, c: locale, m: company

#3144 fix(image): fix dataUri with type svg-base64 in browsers
  src/internal/base64.ts
  src/modules/image/index.ts
  test/internal/base64.spec.ts
Labels: c: bug, p: 1-normal, m: image
