Repository faker-js/faker, pull requests merged in 2025-07, with the labels that each got.

#3536 infra: stop using node 18
  .github/workflows/ci.yml
Labels: c: infra

#3542 infra: use import.meta.dirname
  eslint.config.ts
  scripts/apidocs/utils/paths.ts
  scripts/generate-locales.ts
  test/scripts/apidocs/verify-jsdoc-tags.spec.ts
Labels: c: infra

#3540 feat!: esm only
  CONTRIBUTING.md
  docs/contributing/submit-a-pull-request.md
  docs/guide/index.md
  package.json
  test/require.spec.cts
  tsup.config.ts
Labels: c: refactor, breaking change

#3553 refactor!: remove deprecations
  README.md
  docs/api/ApiIndex.vue
  docs/guide/frameworks.md
  src/faker.ts
  src/modules/date/index.ts
  src/modules/finance/index.ts
  src/modules/helpers/eval.ts
  src/modules/image/index.ts
  src/modules/internet/index.ts
  test/modules/__snapshots__/finance.spec.ts.snap
  test/modules/__snapshots__/image.spec.ts.snap
  test/modules/__snapshots__/internet.spec.ts.snap
  test/modules/date.spec.ts
  test/modules/finance.spec.ts
  test/modules/helpers-eval.spec.ts
  test/modules/helpers.spec.ts
  test/modules/image.spec.ts
  test/modules/internet.spec.ts
  test/scripts/apidocs/__snapshots__/verify-jsdoc-tags.spec.ts.snap
  test/scripts/apidocs/verify-jsdoc-tags.spec.ts
Labels: c: refactor, breaking change

#3561 infra: more precise engines field
  package.json
Labels: p: 1-normal, c: infra

#3560 refactor(word)!: change default error strategy to 'fail'
  docs/guide/upgrading.md
  src/modules/word/filter-word-list-by-length.ts
  src/modules/word/index.ts
  test/modules/__snapshots__/word.spec.ts.snap
  test/modules/word.spec.ts
Labels: p: 1-normal, c: refactor, breaking change, m: word
